Post Categories Selection Fix
wordpress-mobile/WordPress-Android pull request #11025
Opened 2019-12-25 02:20 UTC by jd-alexander

Fixes #9887 

## Findings

When the post is fetched from the `PostStore` it's returning a `post` that has different category types. So sometimes it returns one that has the selected categories and another that has the default. I tried to investigate what could be causing this but I haven't found the solution as yet. 

## Solution
1. I simply replaced the checkmark drawables with new ones that are similar to that of a checkbox so that the component & code could remain intact.

Before | After 
--------|-------
<img src="https://user-images.githubusercontent.com/1509205/71429122-0d18d280-2693-11ea-9796-17fc57e3f504.png" width="320">        |       <img src="https://user-images.githubusercontent.com/1509205/71429123-0d18d280-2693-11ea-91c1-b4ea701d9c47.png" width="320">

## Testing
1. Go to a post. 
2. Go to post settings. 
3. Go to Categories and Tags and select Categories. 
4. Select multiple categories and return to the previous screen and back. 

## Reviewing 
Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] If it's feasible, I have added unit tests.

2019-12-27 17:39 UTC, jd-alexander commented
To reviewers, this PR is still a draft because it hasn't addressed one of the bugs that's described in the issue. Nonetheless, I wanted some feedback about the approach of simply replacing the drawables and if you also had any idea why the `post` issue described above would occur. Let me know. 😄

2019-12-30 21:09 UTC, theck13 requested changes
The code works as expected.  There are a few optimizations we can make if that's within the scope of these changes.

We should follow the [Drawable Resources](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/docs/using-android-resources.md#drawable-resources) guidelines for naming convention of drawables.  That means `check_box_outline.xml` and `checkbox_blank_outline.xml` would be `ic_check_box_white_24dp.xml` and `ic_check_box_outline_white_24dp.xml`, respectively.  Even though those names aren't necessarily the most understandable and adding something like `checked` and `unchecked` may be more descriptive, we want to use the name given by the source repository so others can more easily use the name to lookup the original icon in the future.

We can update the `category_checkmark.xml` file too.  If we want to keep the existing behavior where the checked icon is always shown unless the item is not checked and not pressed, then we can simplify the file as follows:

```xml
<selector
    xmlns:android="http://schemas.android.com/apk/res/android">

    <item android:drawable="@drawable/ic_check_box_outline_white_24dp" android:state_checked="false" android:state_pressed="false" />
    <item android:drawable="@drawable/ic_check_box_white_24dp" />

</selector>
```

If we want to change the behavior so that the opposite icon is shown when the item is pressed, then we can update the file as follows:

```xml
<selector
    xmlns:android="http://schemas.android.com/apk/res/android">

    <item android:drawable="@drawable/ic_check_box_white_24dp" android:state_checked="false" android:state_pressed="true" />
    <item android:drawable="@drawable/ic_check_box_white_24dp" android:state_checked="true" android:state_pressed="false" />
    <item android:drawable="@drawable/ic_check_box_outline_white_24dp" android:state_checked="true" android:state_pressed="true" />
    <item android:drawable="@drawable/ic_check_box_outline_white_24dp" android:state_checked="false" android:state_pressed="false" />

</selector>
```

We should to ask the designers which behavior they prefer so we'll want to add the `[Status] Needs Design Review` label to this pull request.

We'll want to mimic the code style of other icons in the vector drawable files.  To do that, they would end up like this:

```xml
<vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:height="24dp"
    android:width="24dp"
    android:viewportHeight="24.0"
    android:viewportWidth="24.0" >

    <path
        android:fillColor="@android:color/white"
        android:pathData="M19,3H5A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5A2,2 0 0,0 19,3M19,5V19H5V5H19M10,17L6,13L7.41,11.58L10,14.17L16.59,7.58L18,9" >
    </path>

</vector>
```

```xml
<vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:height="24dp"
    android:width="24dp"
    android:viewportHeight="24.0"
    android:viewportWidth="24.0" >

    <path
        android:fillColor="@android:color/white"
        android:pathData="M19,3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3M19,5V19H5V5H19Z" >
    </path>

</vector>
```

Notice that the `android:fillColor` attribute value is changed to `@android:color/white`.  That is intentional so that we can use a single drawable resource and tint the icon for each specific use case.  Unless the icon cannot be tinted (e.g. `ic_bell_blue_wordpress_48dp.xml` used for an app shortcut icon), we should use white as the fill color.  For that reason, we should keep the `android:checkMarkTint` attribute for the `CheckedTextView` view in the `categories_row` layout.  If we want to keep the current color scheme, we'll want to keep the `@color/neutral` value.  If we want to use the `colorControlNormal` attribute, we'll want to update the `categories_row.xml` file like this: 

```xml
<org.wordpress.android.widgets.CheckedLinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/categoryRow"
    android:clickable="false"
    android:layout_height="@dimen/category_row_height"
    android:layout_width="fill_parent"
    android:orientation="horizontal">

    <CheckedTextView
        android:id="@+id/categoryRowText"
        android:checkMark="@drawable/category_checkmark"
        android:checkMarkTint="?attr/colorControlNormal"
        android:gravity="center_vertical"
        android:layout_height="fill_parent"
        android:layout_width="fill_parent"
        android:orientation="vertical"
        android:textColor="?attr/wpColorText"
        android:textSize="@dimen/text_sz_large"
        tools:text="Category">
    </CheckedTextView>

</org.wordpress.android.widgets.CheckedLinearLayout>
```

That's another thing we should ask the designers.

2020-01-06 17:18 UTC, jd-alexander commented
Thanks for the review @theck13 I really appreciate how thorough you have explained this all 😄. I will be making the suggested changes and then tagging the design team once I am done 👍

2020-01-07 19:26 UTC, jd-alexander commented
For design review, below is a video of the way how the checkmark icon's state behaviors in reaction to direct actions. 

1. When the user presses the category the icon appears checked but becomes unchecked if a full press isn't done. (1s - 6s) 
2. When the user presses the category the icon is checked and to make it unchecked the user presses it again (9s - 18s)

Checkmark checked and pressed state video |
--------|
[Video Link](https://drive.google.com/file/d/19Irc-nM8KCtmRgK_ao6P-RpXokzMhEVN/view?usp=sharing)        |

2020-01-07 19:31 UTC, jd-alexander commented
@theck13 do you have any thoughts about the bug under "Findings" I am gonna do another investigation to see if I can figure out what's happening but was just wondering if you have any thoughts 😄

2020-01-07 19:36 UTC, theck13 commented
I'm not sure why the `PostStore` would return different categories.  Maybe the store hasn't been  synced before the `Post` object is retrieved?  That _may_ be why the categories have the default  values sometimes.

2020-01-07 19:38 UTC, jd-alexander commented
> I'm not sure why the PostStore would return different categories. Maybe the store hasn't been synced before the Post object is retrieved? That may be why the categories have the default values sometimes.

Interesting. Thanks. What odd is if you are on that screen you will see the categories selected and if you press back and then reopen they are unselected and if you do the same action again it gets reselected so it's like every other time the categories isn't properly propagated.

2020-01-07 20:05 UTC, mattmiklic commented
> For design review, below is a video of the way how the checkmark icon's state behaviors in reaction to direct actions.

Thanks for the ping @jd-alexander! I think this works pretty well overall. In terms of visual styling, it would be nice if we could use the checkbox layout and appearance that's defined in the Material Design spec: https://material.io/components/selection-controls/#checkboxes

- 24px square boxes
- When unchecked, boxes have a neutral gray outline
- When checked, boxes have no outline, are filled with the primary color, and have a white checkmark
- Boxes sit to the left of their text label (rather than along the right-hand edge)
- Boxes sit on the 16dp keyline; their text labels sit on the 72dp keyline.

The link above has more detail on styling of checkboxes in a disabled, hover, focus, and pressed state.

2020-01-13 16:29 UTC, jd-alexander commented
Hi @mattmiklic I made the changes you suggested! The `CheckBox` component in Android is utilizing the Material Design Library that Google created so all the styles and behavior are built in. Below are some screenshots of the new layout. 

Pressed & Unchecked | Pressed & Checked 
--------|-------
<img src="https://user-images.githubusercontent.com/1509205/72272827-450e9800-35f7-11ea-9333-4edc55bfb737.png" width="320">        | <img src="https://user-images.githubusercontent.com/1509205/72272829-45a72e80-35f7-11ea-97af-e4897830c90c.png" width="320">

LTR | RTL 
--------|-------
<img src="https://user-images.githubusercontent.com/1509205/72272828-45a72e80-35f7-11ea-9e30-232b67213b52.png" width="320">        |     <img src="https://user-images.githubusercontent.com/1509205/72272830-45a72e80-35f7-11ea-949f-1faa80791ebf.png" width="320">

2020-01-13 16:30 UTC, jd-alexander commented
Hey, @theck13 👋 so I recreated the layout and utilized the `CheckBox` so the drawables are no longer needed. Let me know what you think about the changes.

2020-01-13 20:37 UTC, theck13 requested changes
There are code style issues in the `categories_row.xml` file.  While they may not be flagged with Checkstyle, they don't follow the style of other XML layout files and there is even inconsistency within `categories_row.xml` itself.  There are no functional downsides to the code style issues, but there can be human readability issues.  Thus, it's best to follow the other XML layout files for code style consistency.

Are there any benefits to changing the layout and creating the new class `CheckedConstraintLayout` over keeping the existing `CheckedLinearLayout`?

Even though 16dp and 72dp paddings are used for the checkbox and text views, they are not vertically aligned with the back arrow and title text in the app bar.  `CheckBox`es have approximately 8dp padding built in to the view to help with things like the touch ripple, which makes them slightly off-center when compared with the back arrow above when using 16dp left/start padding.  There is 16dp of padding added to the `TextView` programmatically based on the level of the category so that you can see which categories have a parent/child relationship.  With the new layout, that causes the category text to be misaligned with the ***Select categories*** title in the app bar.  We can correct for that as shown in the ***Align*** screenshots below, but I find the lack of indentation of the checkbox for child categories to be visually confusing.  It's very easy to miss that a category is a child if you're scanning the list especially if you have more than a few categories.  An alternate solution would be to indent the entire row layout programmatically similar to the way the `TextView` is done currently.  Unfortunately, that makes the checkboxes and text misaligned with the back arrow and title in the app bar.  @mattmiklic, what do you think is best?  See the screenshots below for illustration.

![11025](https://user-images.githubusercontent.com/3827611/72289531-8f4c4500-3608-11ea-98fb-10fd806d3df5.png)

2020-01-13 21:33 UTC, mattmiklic commented on WordPress/src/main/res/values/dimens.xml
> +    <dimen name="row_text_keyline">72dp</dimen>
Thanks for implementing these changes @jd-alexander and thanks to @theck13 for these suggestions. I think either the "Align" or "Alternate" options shown above would work. The "Alternate" view with the indented child checkbox is a little more visually cluttered, but agree that it makes it easier to denote child categories at a glance. Let's go with that if it's technically feasible; if for any reason it's not we can use the "Align" style shown here.

2020-01-14 00:53 UTC, jd-alexander commented on WordPress/src/main/res/values/dimens.xml
> +    <dimen name="row_text_keyline">72dp</dimen>
Thanks @mattmiklic I will go with the "Alternate" approach and let y'all know how it goes.

2020-01-14 00:57 UTC, jd-alexander commented
Thanks again for another review @theck13 I really appreciate it 🙌 

> There are code style issues in the categories_row.xml file. While they may not be flagged with Checkstyle, they don't follow the style of other XML layout files and there is even inconsistency within categories_row.xml itself. There are no functional downsides to the code style issues, but there can be human readability issues. Thus, it's best to follow the other XML layout files for code style consistency.

Thanks! I will do another run through. Consistency is of utmost importance for codebases of this nature 😉 

> Are there any benefits to changing the layout and creating the new class CheckedConstraintLayout over keeping the existing CheckedLinearLayout?

I created the new layout due to the mention of the keyline usage by Matt and since  `Guidelines` are a good approach to replicating the keyline behavior I opted to use a `ConstraintLayout` since that's the preferred way to create layouts in Android these days. It was after creating the layout I truly realized the purpose of the `CheckedLinearLayout` for the `ListView`'s item checking functionality and decided to let created the `CheckedConstraintLayout`. I also didn't see any other usages of `CheckedLinearLayout` so it felt like a change without any side effects. 

> Even though 16dp and 72dp paddings are used for the checkbox and text views, they are not vertically aligned with the back arrow and title text in the app bar. CheckBoxes have approximately 8dp padding built in to the view to help with things like the touch ripple, which makes them slightly off-center when compared with the back arrow above when using 16dp left/start padding. There is 16dp of padding added to the TextView programmatically based on the level of the category so that you can see which categories have a parent/child relationship. 

Makes sense! Thanks for expounding on this! 

> With the new layout, that causes the category text to be misaligned with the Select categories title in the app bar. We can correct for that as shown in the Align screenshots below, but I find the lack of indentation of the checkbox for child categories to be visually confusing. It's very easy to miss that a category is a child if you're scanning the list especially if you have more than a few categories. An alternate solution would be to indent the entire row layout programmatically similar to the way the TextView is done currently. Unfortunately, that makes the checkboxes and text misaligned with the back arrow and title in the app bar. @mattmiklic, what do you think is best? See the screenshots below for illustration.

Thanks for these screenshots! For the implementation, I will be

1. Creating a `8dp` keyline for the `CheckBox` since it has another `8dp` internally.
2. Adding the `16dp` padding to the entire row when a node has a parent. 
3. Making the style changes.

2020-02-10 22:22 UTC, jkmassel commented
We're freezing `14.2` today, so this PR is being bumped to `14.3`. If you'd like it to ship with `14.2`, please merge it into `release/14.2` and ping me – I'll be happy to cut a new beta release.

2020-02-20 23:37 UTC, oguzkocer commented
Hey @jd-alexander! It looks like there hasn't been any updates on this PR for a while, could you have a look at it once you get a chance? If it's on hold for now, if you can also update the milestone with its intended version, that'd be great!

2020-02-21 00:03 UTC, jd-alexander commented
> Hey @jd-alexander! It looks like there hasn't been any updates on this PR for a while, could you have a look at it once you get a chance? If it's on hold for now, if you can also update the milestone with its intended version, that'd be great!

Hey @oguzkocer ! I paused the work here since the material design/dark mode work was being done and these files would be touched. Once the material theme is merged into `develop` I will continue so I will bump the milestone further.

2020-02-21 01:05 UTC, oguzkocer commented
Thanks for the update and bumping the release version @jd-alexander!

2020-03-12 19:22 UTC, jd-alexander commented
Closing this for now as the UI for the categories changed and alot of the commits in this won't be needed to transfer the material design UI changes. Will keep the branch around nonetheless.

2020-03-12 19:22 UTC, closed without merging