Fixing support for reader page jump
wordpress-mobile/WordPress-Android pull request #12574
Opened 2020-07-31 15:52 UTC by develric

Fixes #7654 

Inspired by a @khaykov comment [here](https://github.com/wordpress-mobile/WordPress-Android/issues/7654#issuecomment-640883823) I tried to further explore that solution in this PR.

Result seems good enough I think

<p align="center">
  <img width="300" src=https://user-images.githubusercontent.com/47797566/89052144-909b5000-d355-11ea-8798-f614de6e8a62.gif>
</p>

## To test

You can use this link to the post shown in the gif https://demo2020061600.wordpress.com/2020/07/31/up-bottom-2/
- check the page jump up to bottom works
- check the page jump bottom up works
- check the external link works
- smoke test the reader post detail

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-08-03 20:04 UTC, khaykov requested changes
@develric thanks for taking over this! It works amazingly 👍 

I noticed just one issue - if the anchor does not exist on the webpage, tapping on the link will crash the app:

```
org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android, PID: 19162
    java.lang.NumberFormatException: For input string: "null"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at org.wordpress.android.ui.reader.ReaderPostDetailFragment$onPageJumpClick$1.onReceiveValue(ReaderPostDetailFragment.kt:1513)
        at org.wordpress.android.ui.reader.ReaderPostDetailFragment$onPageJumpClick$1.onReceiveValue(ReaderPostDetailFragment.kt:129)
        at hm.a(Unknown Source:2)
        at org.chromium.android_webview.AwContents.a(PG:1020)
        at zp.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

2020-08-03 20:04 UTC, khaykov commented on WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
> +            val yOffset = (readerWebView.scale * it.toFloat()).toInt()
AS tells me that scale getter is deprecated. Do you think we can use an alternative? StackOverflow suggests `getResources().getDisplayMetrics().density`, but I haven't tried it :)

2020-08-06 00:05 UTC, develric commented
Hey @khaykov 👋! Thanks for the review and spotting that issue 🙇‍♂️. I tried to fix it (also adding a Toast in case the landing page jump cannot be found). Your suggestion on using `density` seems to work well for me 😊 ! Let me know and thanks 🙇‍♂️!

PS: updated the test page to include a jump to a missing anchor reference if it can come handy for testing.

2020-08-07 05:16 UTC, khaykov approved these changes
Thanks for the fix! Works well 👍

2020-08-07 05:16 UTC, merged