AppBar refresh - Reader and Notifications
wordpress-mobile/WordPress-Android pull request #12743
Opened 2020-08-21 05:24 UTC by khaykov

This PR updates AppBar design and adds lift on scroll functionality to the following screens (and related nested screens):

- Reader
- Notifications

Main Reader and Notification screens accessible from the bottom nav are already updated, so no need to check them.

To test:

For all screens:
- Make sure nothing looks out of place (including ActionMode) :)
- Make sure the toolbar state is restored on configuration change.

Test 1:

Navigate to the Reader.
Check the following screens, and make make sure that lift on scroll works:
- Search (there is a pre-existing issue with the whole AppBAr being focused alongside the search input field).
- Blog's post list.
- Post details (+swipe right/left in ViewPager)
- Post Comments
- Post "Liked By" screen.

Test 2:

Navigate to the Notifications.
- Check various notification detail pages and make sure that lift on scroll works  (+swipe right/left in ViewPager).
- Check Notification settings.

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-08-24 10:10 UTC, oguzkocer commented
Hi there! `15.5` is being frozen, so this PR is being bumped to `15.6`. If these changes _have to_ be shipped with `15.5`, please target `release/15.6` and cc me in the PR so I can cut a new beta release. Also if you can keep the release dates in mind and bump the PRs & issues you are working on before the code freeze date, we'd really appreciate it.

_This is a standard release version bump message. Let me know if you have any feedback._

---

@khaykov A few extra notes:

1. The PR doesn't have any reviewers assigned to it, please make sure to do so when you open the PR or keep it as a draft otherwise.
2. `PR submission checklist:` is not completed. We want to make sure developers are aware of these checklist items and actively think about them before the PR is marked ready for review.
3. This PR is against a feature branch, so a milestone is not necessary.
4. A PR that's against a feature branch at the last day of the sprint is very unlikey to be merged before the code freeze, so it'd have been better to not add a milestone at all.

All these have been explained recently in a p2 post and brought up several times in different PRs. We'd appreciate it if you can keep all this in mind for the next time. Thank you!

2020-09-01 11:44 UTC, planarvoid requested changes
Thanks for the changes @khaykov, the changes look great :-) I've been testing this PR and I've found a few bugs: 

- Go to Reader/Search results
- Scroll in one of the tabs 
- Switch tabs back and forth
- The shadow disappears


- Go to comments (the same goes for the Liked By screen, Notifications settings screen)
- Scroll down to show the shadow
- Rotate the device
- The shadow disappears

2020-09-01 21:17 UTC, khaykov commented
@planarvoid Thank you so much for the review! I fixed the AppBar shadow on the comment list. 

Regarding the reader search, the behavior you are seeing is intended, and there are two parts to it:
- When the recycler view can't scroll vertically the shadow is not visible. Each tab contains its own recycler view, and when you switch between them the AppBar reflects the scrolling state of each tab.
- Related to ⬆️  - there is a Reader-specific (it think so) behavior - when you return to the list, Reader is scrolling to show the topmost post in full - so if you scroll the first post a bit, so let's say, half of it is out of the view, navigate to a different tab and return back, the post will be scrolled to the top, which will also be the top of the recycler view, so the shadow will not be there, since the list can no longer scroll up.

Hope this makes sense 👍

2020-09-09 07:41 UTC, planarvoid commented
thanks for the fixes @khaykov ! I think you've overlooked part of the original second bug :-) The bug appears also in the Liked By screen and the Notifications settings screen. You've fixed it in the Comments screen (and it works well there). 
About the first bug - The behaviour is a little bit weird but I'm mostly getting the shadow now when switching the tabs (I swear it's not there 100% of time but I can't reliably reproduce it). I think we can consider that one as fixed :-). It's a very edgecasey thing.

2020-09-09 16:50 UTC, khaykov commented
> I think you've overlooked part of the original second bug :-) The bug appears also in the Liked By screen and the Notifications settings screen. 

Oh, man, this is embarrassing! 🤦 Fixed it. Thank you so much for your patience!

2020-09-10 07:33 UTC, planarvoid approved these changes
No worries at all! :-) It looks good now 👍 , thanks for the fixes

2020-09-10 07:33 UTC, merged