Feature/build screenshots on ci
wordpress-mobile/WordPress-Android pull request #12869
Opened 2020-09-02 16:24 UTC by loremattei

This PR makes it possible to build the screenshots on CI. The PR itself is pretty big, but it's the final result of a trial project, so the various parts have been already reviewed. 

To test:
- The job can be started with this cURL call: 
```
curl -u <your_token>: -X POST --header "Content-Type: application/json" -d '{
 "branch": "feature/screenshots-phase1",
 "parameters": {
   "generate_screenshots": true
 }
}' https://circleci.com/api/v2/project/github/wordpress-mobile/WordPress-Android/pipelinegeorge:WordPress-Android
```

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-09-02 16:32 UTC, AliSoftware commented
Actually, I've included a lane to trigger the job, so to test it you can just use this:
```
bundle exec fastlane trigger_screenshots token:<yourtoken> branch:feature/build-screenshots-on-ci
```

2020-09-02 16:45 UTC, AliSoftware requested changes
Not sure if we should just disable `fr-CA` for `promo_config` or remote the line entirely, but keeping it will make the job fail, not finding raw screenshots for that locale when trying to generate the corresponding promo screenshots.

2020-09-02 16:45 UTC, AliSoftware commented on .circleci/config.yml
> +          locales: ar de_DE en_US es_ES fr_FR iw_IL in it_IT ja_JP ko_KR nl_NL pl_PL pt_BR ru_RU sr sv_SE th tr_TR vi zh_CN zh_TW
Leftover from when you re-enabled all locales from my limited list of 2 I guess; no need to keep the commented line now that it's the same as the uncommented one.
```suggestion
          locales: ar de_DE en_US es_ES fr_FR iw_IL in it_IT ja_JP ko_KR nl_NL pl_PL pt_BR ru_RU sr sv_SE th tr_TR vi zh_CN zh_TW
```

2020-09-02 16:45 UTC, AliSoftware commented on fastlane/Fastfile
> +  { glotpress: "fr",    google_play: "fr-CA",  promo_config: {} },
This one is not part of [the list of `locales:` parameter from circleci config](https://github.com/wordpress-mobile/WordPress-Android/pull/12869/files#diff-1d37e48f9ceff6d8030570cd36286a61R392) and should thus be excluded from promo screenshots
```suggestion
  { glotpress: "fr",    google_play: "fr-CA",  promo_config: false },
```

(Alternatively, maybe we could remove that line entirely to only keep `fr-FR`?)

2020-09-02 18:47 UTC, oguzkocer commented
Hey @loremattei @AliSoftware! I probably won't get a chance to review this until my first full day working which is on Saturday. That is unless its review is urgent, so please let me know if you want me to prioritize it.

2020-09-03 22:18 UTC, AliSoftware commented
Note: for reference, merging this PR should close #12601
_(I don't have the permissions to edit the PR and link it to the issue)_

2020-09-04 03:26 UTC, jkmassel approved these changes
This generally worked quite well!

The screenshots were captured, processed and composited. I have a few next steps that will need to be addressed before we can use it in production. Given the size of this PR already, I don't see why it can't be a separate one.

![4-check-whats-happening-in-real-time](https://user-images.githubusercontent.com/1123407/92196026-8fb17e80-ee2b-11ea-9728-7d74d67cb737.png)
There seems to be something wrong with the opacity layer when compositing the image. This may be related to the ImageMagick 7 upgrade.

Also note in the above screenshot that the font isn't correct.

![3-track-what-your-visitors-love](https://user-images.githubusercontent.com/1123407/92196065-a5bf3f00-ee2b-11ea-90c8-d0bfe122b9a8.png)
On tablet sizes, the screenshot image is stretched in the above screenshot


Also, somewhat weirdly; [this page shows success](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-Android/15965/workflows/9e32160f-d1ea-470f-b760-7b690bd989fe) across the board, while [this page shows](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-Android/15965/workflows/9e32160f-d1ea-470f-b760-7b690bd989fe/jobs/71017/tests) that 3 tests failed. This is probably related to the `fr-CA` locale that @AliSoftware mentioned earlier.

Again, I don't think these are blockers – this is generally a very good PR, but we should come back to it soon so that we can start using them soon :)

2020-09-04 07:27 UTC, AliSoftware commented
> Also note in the above screenshot that the font isn't correct.

This might be because the font referenced in `fastlane/playstoreres/assets/*.css` are missing and will need to be installed. @oguzkocer mentioned that case in a post earlier this month.

> On tablet sizes, the screenshot image is stretched in the above screenshot

I'm wondering if I used the right orientation for the tablet device in `.circleci/config.yml`. It might be capturing raw screenshots in portrait, while the promo screenshots are rendering them I  landscape. If that's indeed the issue, could be a fix we apply directly in this PR

2020-09-04 07:31 UTC, AliSoftware commented on .circleci/config.yml
> +            model=gts3lltevzw,version=28,orientation=default
After seeing @jkmassel's comment on screenshots being stretched when rendered in promo material, we might want to enforce the right orientation here

```suggestion
            model=gts3lltevzw,version=28,orientation=landscape
```

2020-09-04 12:09 UTC, loremattei commented
I agree with @jkmassel that this is already quite a big PR. 
@rachelmcr since you'll work on updating the screenshots soon, you may have a chance to fix the issues above.

2020-09-04 12:09 UTC, merged

2020-09-04 12:09 UTC, loremattei commented
Thanks @AliSoftware for this work!

2020-09-05 14:15 UTC, oguzkocer commented
Just noting here that I had a quick look through the changes and it looked great. Thank you for this work @AliSoftware! 🥳