Improvement: Reader: Add sorting option to Discover or Topics
wordpress-mobile/WordPress-Android pull request #14109
Opened 2021-02-18 17:00 UTC by KaungMyat-Min

# Feature
When the user is on the Discover screen, they are given the option to sort the posts by popularity or most recent.

## To do:
- implement ui components
- add unit tests for changing sorting types

## To test
- verify the pre-defined unit tests pass

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-02-19 11:14 UTC, ashiagr requested changes
Thanks for working on it @kaung-myat-min! Changes looks nice overall, its great that you could understand the code and put all the pieces together 👍.

I've left few comments/questions/warnings for you to consider. Most are minor, marked some with ⚠️ which can either lead to a crash or alter the behaviour.

2021-02-19 11:14 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/datasets/ReaderDiscoverCardsTable.kt
> +    fun clear(DiscoverSortingType: DiscoverSortingType) {
Minor 🔍: Typo, `DiscoverSortingType` variable name should be camelCased.
Same applies on line 50
`fun addCardsPage(cardsJson: String, DiscoverSortingType: DiscoverSortingType) {`

2021-02-19 11:14 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/datasets/ReaderDiscoverCardsTable.kt
> +                        " $CARDS_SORTING_TYPE_COLUMN TEXT" +
Warning ⚠️: This column will not be added to the table due to missing comma on the previous line.

App crashes with the logs: 
```
android.database.sqlite.SQLiteException: no such column: cards_sorting_type (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM tbl_discover_cards WHERE cards_sorting_type = ? ORDER BY _id ASC
```

2021-02-19 11:14 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/datasets/ReaderDiscoverCardsTable.kt
> +        getWritableDb().delete(DISCOVER_CARDS_TABLE, whereClause, args)
Warning ⚠️:  Delete query translates to 

```
DELETE FROM tbl_discover_cards WHERE WHERE cards_sorting_type = ?kotlin.Unit      
```

with duplicate `WHERE`.  Also log statement gets appended to where clause resulting in a `kotlin.Unit` addition at the end.

Crash logs:

```
FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: org.wordpress.android.prealpha, PID: 28900
    android.database.sqlite.SQLiteException: near "kotlin": syntax error (code 1 SQLITE_ERROR): , while compiling: DELETE FROM tbl_discover_cards WHERE cards_sorting_type = ?kotlin.Unit
```

2021-02-19 11:14 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModel.kt
> +    private val _sortingType = MutableLiveData<DiscoverSortingType>(POPULARITY)
Minor 🔍: (IDE warning) Explicit type argument `DiscoverSortingType` can be removed .

```suggestion
    private val _sortingType = MutableLiveData(DiscoverSortingType.POPULARITY)
```

2021-02-19 11:14 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverLogic.kt
> +        ReaderDiscoverCardsTable.clear(sortingType)
Question ❓: Here post ids for only selected `sortingType` will be cleared from `ReaderDiscoverCardsTable` but _all_ discover posts will be deleted from the `ReaderPostTable` in the following line:
`ReaderPostTable.deletePostsWithTag(ReaderTag.createDiscoverPostCardsTag())`

Are we aiming to store post ids for each sort type in the `ReaderDiscoverCardsTable` or just the last one?

2021-02-19 11:14 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/util/config/FilterDiscoverFeatureConfig.kt
> +@Feature(remoteField = FILTER_DISCOVER, defaultValue = true)
There are two sections "Remote features" and "Features in development" in the "Test feature configuration" screen. We need to use `@FeatureInDevelopment` annotation here similar to the sample code I shared. 

Apologies, I didn't make this clear, I understand it is difficult to notice without context.

2021-02-19 11:14 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverServiceStarter.kt
> +            extras.putInt(ARG_SORTING_TYPE, task.ordinal)
Warning ⚠️: Passing ordinal of a wrong enum:

```suggestion
            extras.putInt(ARG_SORTING_TYPE, sortingType.ordinal)
```

2021-02-19 11:14 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverServiceStarter.kt
> +    const val ARG_SORTING_TYPE = "sortingType"
```suggestion
    const val ARG_SORTING_TYPE = "sorting_type"
```

2021-02-26 11:12 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/datasets/ReaderDiscoverCardsTable.kt
> +    fun clear(DiscoverSortingType: DiscoverSortingType) {
Fixed in 15bba09

2021-02-26 11:13 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/datasets/ReaderDiscoverCardsTable.kt
> +        getWritableDb().delete(DISCOVER_CARDS_TABLE, whereClause, args)
Fixed in 15bba09

2021-02-26 11:13 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModel.kt
> +    private val _sortingType = MutableLiveData<DiscoverSortingType>(POPULARITY)
Fixed in 860c8f3

2021-02-26 11:14 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverServiceStarter.kt
> +            extras.putInt(ARG_SORTING_TYPE, task.ordinal)
Fixed in 609d151

2021-02-26 11:14 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverServiceStarter.kt
> +    const val ARG_SORTING_TYPE = "sortingType"
Fixed in 609d151

2021-02-26 11:25 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverLogic.kt
> +        ReaderDiscoverCardsTable.clear(sortingType)
Fixed in 18bbeb3

2021-02-26 11:31 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/datasets/ReaderDiscoverCardsTable.kt
> +                        " $CARDS_SORTING_TYPE_COLUMN TEXT" +
@kaung-myat-min, thanks for adding missing comma in 15bba09 but I now see that semi-colon at the end is giving a syntax error.

`Result: near ";": syntax error`

 ```
" $CARDS_SORTING_TYPE_COLUMN TEXT DEFAULT ${DiscoverSortingType.NONE.sortedBy};" +
")"
```
Can we make this small correction by placing it after the closing bracket on the next line?

2021-02-26 11:34 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverLogic.kt
> +     * - Posts are not deleted because they are used in other sorting type and they will be deleted on purging.
Thank you for this!

2021-02-26 12:45 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/util/config/FilterDiscoverFeatureConfig.kt
> +        FILTER_DISCOVER
While feature is in development, we don't need this third param `FILTER_DISCOVER`. 

```
* @param remoteField is the key of the feature flag in the remote config file, only set this field when there is a
* remote flag available
```

Let's just have below in the config file: 

```
@FeatureInDevelopment
class FilterDiscoverFeatureConfig
@Inject constructor(appConfig: AppConfig) : FeatureConfig(
        appConfig,
        BuildConfig.ENABLE_FILTER_FOR_DISCOVER
) 
```

2021-03-01 04:34 UTC, KaungMyat-Min commented on WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverLogic.kt
> +     * - Posts are not deleted because they are used in other sorting type and they will be deleted on purging.
Glad, it is useful.

2021-03-02 05:20 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/datasets/ReaderDiscoverCardsTable.kt
> +                        " $CARDS_SORTING_TYPE_COLUMN TEXT" +
Fixed in ce8343c

2021-03-02 05:21 UTC, merged