jetpack: backup download notice banner
wordpress-mobile/WordPress-Android pull request #14147
Opened 2021-02-24 20:09 UTC by zwarm

Fixes #14030 

This PR adds the Backup Download Banner to the activity log list and backup list.

Notable changes ( It may be easiest to review this PR by commits and I'm available if reviewer wants to pair review)
- `activity_log_list_notice_item.xml` - New layout file for the notice banner
- `styles.xml` & `strings.xml` - Added new styles for the banner and a few strings
- `ActivityLogAdapter`, `ActivitiyLogDiffCallback` - both updated to support the `Notice` list item type and the new `NoticeItemViewHolder`, so that the view will actually show in the list
- Updated `Complete` to include *url* and *validUntil* and `GetBackupDownloadStatusUseCase` to send those values downstream
- Created `PostDismissBackupDownloadUseCase` which is post the dismiss request to the server. If there is an error, we log it and move on.
- Four new tracking collections points were added to track button taps from the notice banner. Separate tracks for activity log list notice vs backup list notice. 
      JETPACK_BACKUP_DOWNLOAD_FILE_NOTICE_DOWNLOAD_TAPPED - 
      JETPACK_BACKUP_DOWNLOAD_FILE_NOTICE_DISMISSED_TAPPED,
      ACTIVITY_LOG_DOWNLOAD_FILE_NOTICE_DOWNLOAD_TAPPED,
      ACTIVITY_LOG_DOWNLOAD_FILE_NOTICE_DISMISSED_TAPPED
 - Added a couple of new function to `ActivityLogTracker` to make the tracks call reusable
 - Added a new navigation event for `DownloadBackupFile`, which will forward the user to the web browser for file download. Updated the observer in `ActivityLogListFragment` to handle the browser launch
 - Added a `JetpackBackupDownloadActionState` which will let the calling activity know which state the download is in on return. This was a precursor to showing the correct messaging when returning to the activity log list or backup list. Changes were made to `BackupDownloadFragment` and `BackupDownloadViewModel` to support this new intent extra.
 - The majority of the changes occur in `ActivityLogViewModel`, which include:
 - - Updating `backupDownloadEvent` with a *displayNotice* field, so when `reloadEvents` executes it uses this property to determine if the notice banner should be shown. Also included downloadId, url, and validUntil.
 - - Removed the showBackupDownloadFinishedMessage from within reloadEvents, the snackbar is replaced with the notice banner
 - - Added a new function to build the notice list item
 - - Added two new functions to handle the *download* and *dismiss* button clicks from within the notice banner 
 - - Updated `onQueryBackupDownloadStatus` to use the JetpackBackupDownloadActionState to determine which snackbar message to be shown. Note that in the case of returning to the lists, we do want to show the snackbar in addition to the notice banner.
 - - Updated `handleBackupDownloadStatusForProgress` to no longer check if the progress item is shown, we always kick off a reloadEvents
 - - Updated `handleBackupDownloadStatusForComplete` to reloadEvents of the progressItem is not shown
 - Updated and/or added tests

**Merge Instructions:**
- Still need to decide which milestone to base against, so please do not merge yet
- Review [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1891)  merge and create a tag in FluxC develop
- Replace FluxC hash with tag from develop in build.gradle
- Remove the "Not Ready for Merge label"
- Merge this PR

|light |dark
|---|---|
|![light](https://user-images.githubusercontent.com/506707/109054627-18f39080-76ac-11eb-93c4-3f9d6726d72a.png)|![dark](https://user-images.githubusercontent.com/506707/109054631-1abd5400-76ac-11eb-9039-034505782c84.png)

To test: 
#### Scenario.1 : BackupDownload Flow - Manual Exit
* Open app
* Launch `Activity Log` screen,
* Find a rewindable item from the list, click on the ellipsis menu item and select `Download backup` to launch the `Backup Download` screen,
* Click the `Create downloadable file` button.
* Navigate back manually (by clicking the `X` toolbar button or pressing/swiping back).
* You should automatically be navigated back to the `Activity Log` screen and a backup status will be triggered,
* The backup progress item should immediately appears. 
* A snackbar should immediately appear informing that the backup just started. 
* Wait for backup to finish while having the `Activity Log` screen 
* When backup finishes
 - The backup progress item should disappear
 - The backup download notice should appear

#### Scenario.2 : BackupDownload Flow - Wait for flow to end and then exit
* Open app
* Launch `Activity Log` screen,
* Find a rewindable item from the list, click on the ellipsis menu item and select `Download backup` to launch the `Backup Download` screen,
* Click the `Create downloadable file` button.
* Wait for the backup download flow to complete keeping the backup flow process open
* After the backup completes, navigate back manually (by clicking the `X` toolbar button or pressing/swiping back)
* When backup finishes
 - A snackbar should immediately appear informing that the backup is complete
 - The backup download notice should appear

#### Scenario.3 (Notice banner download)
- Run a backup using scenario 1 or 2 above
- Click on the "Download" button within the notice banner
- Note that a browser is launched and the download starts. In some cases, you may be prompted to verify the download.

#### Scenario.4 (Notice banner dismiss)
- Run a backup using scenario 1 or 2 above
- Click on the "Dismiss" button within the notice banner
- Note the the Notice banner disappears

PR submission checklist:

- [X] I have considered adding unit tests where possible.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-02-25 12:31 UTC, ParaskP7 commented
👋 @zwarm !

I have some questions on the second scenario: `Scenario.2 : BackupDownload Flow - Wait for flow to end and then exit`
1) `When backup finishes`: This is just a typo, correct?
1) `A snackbar should immediately appear informing that the backup is complete`: Since in the first scenario, this snackbar is not displayed, we might probably want to do the same here, meaning never showing the finished message?

2021-02-25 12:34 UTC, ParaskP7 commented
👋 @zwarm !

I also tested a fifth scenario, given that was on the video you shared, opening the `Download Backup` notification and clicking the `site's Backups` link for both:
1) When the `Backup Download` notice is showing (not previously dismissed), and
1) When the `Backup Download` notice was dismissed.

Everything works as expected, kudos! 🌟

2021-02-25 12:38 UTC, osullivanchris approved these changes
I went through the 4 flows and tested on tablet and dark mode. All looks exactly as expected, nice work 👌 😃

2021-02-25 13:23 UTC, zwarm commented
> 👋 @zwarm !
> 
> I have some questions on the second scenario: `Scenario.2 : BackupDownload Flow - Wait for flow to end and then exit`
> 
> 1. `When backup finishes`: This is just a typo, correct?

Yes 🤦 

> 2. `A snackbar should immediately appear informing that the backup is complete`: Since in the first scenario, this snackbar is not displayed, we might probably want to do the same here, meaning never showing the finished message?

I decided to leave it because we are returning from another screen, where as in scenario 1 we are already in the context of the list. I could just as easily remove it here too. We need a tie breaker.

2021-02-25 13:58 UTC, ParaskP7 commented
👋 @zwarm !

> I decided to leave it because we are returning from another screen, where as in scenario 1 we are already in the context of the list. I could just as easily remove it here too. We need a tie breaker.

Actually, thinking about it more and having you explained it it makes sense, let's leave it as is for now! 🙏

2021-02-25 16:01 UTC, ParaskP7 requested changes
👋 @zwarm !

I have reviewed and tested this PR as per the instructions, everything almost works as expected, amazing job dealing with this huge fat task! 🌟 🌟 🌟

I have left some minor (🔍) comments and suggestions (💡) for you to consider. Also, I have left a handful of questions (❓) I would like to discuss with you. Most importantly, I have left some warnings (⚠️), but mainly around missing tests. Finally, there is one blocker (🚫) that I would really like us to fix before merging this to `develop`.

🙏

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/ui/jetpack/backup/download/usecases/PostDismissBackupDownloadUseCase.kt
> +    private suspend fun handleError(
Suggestion (💡): I have managed to make this a bit more compact. Feel free to update it to this new version or ignore:
```
    private suspend fun handleError(retryAttempts: Int) = if (retryAttempts >= MAX_RETRY) {
        AppLog.d(T.JETPACK_BACKUP, "$tag: Exceeded $MAX_RETRY retries while dismiss download backup file")
        true
    } else {
        delay(DELAY_MILLIS * max(1, DELAY_FACTOR * retryAttempts))
        false
    }
```

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/ui/jetpack/backup/download/BackupDownloadFragment.kt
> +                    is BackupDownloadCanceled -> Triple(false, null, JetpackBackupDownloadActionState.CANCEL)
Suggestion (💡): Since all of those when entries are multiline, I suggest that become a multiline as well, just for someone to be able to see the diffs straight away. Wdyt? Something like:
```
is BackupDownloadCanceled -> Triple(
        false,
        null,
        JetpackBackupDownloadActionState.CANCEL
)
```

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/ui/jetpack/backup/download/BackupDownloadViewModel.kt
> +            val inProgress: Boolean = true
Question (❓): As far as I understand this `inProgress` and the other one further below are unused, isn't it?

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
> +    private val postDismissBackupDownloadUseCase: PostDismissBackupDownloadUseCase
Minor (🔍): Since this is a backup related use case, consider grouping that below the other backup related use case further above. Wdyt?

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
> +    private var currentBackupDownloadEvent = BackupDownloadEvent(false, displayNotice = false)
Suggestion (💡): Since a named parameter is now used, I suggest updating all of them to match that pattern, like:
```
    private var currentRestoreEvent = RestoreEvent(displayProgress = false)
    private var currentBackupDownloadEvent = BackupDownloadEvent(displayProgress = false, displayNotice = false)
```

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
> +        if (withBackupDownloadNoticeItem) {
Warning (⚠️): Consider adding a test for this case.

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
>          if (backupDownloadEvent.isCompleted) {
1) Question (❓): Why keeping the state is needed here?
2) Question (❓): If keeping the state is necessary, will copying the current state to `displayProgress = false` provide any value? This is due to the fact that the above `currentBackupDownloadEvent = backupDownloadEvent` will already be doing that for us, will it not?
3) Question (❓): If all my above assumptions are correct, probably this whole if logic can be removed altogether.
4) Warning (⚠️): Consider updating the corresponding tests no matter which approach is to be taken.

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
> +                    primaryActionButtonClickListener = this@ActivityLogViewModel::onDownloadBackupFileClicked,
Suggestion (💡): What if those two actions where to be written like the below:
```
primaryAction = { onDownloadBackupFileClicked(backupDownloadEvent.url as String) },
secondaryAction = {  dismissNoticeClicked(backupDownloadEvent.downloadId as Long) }
```

Wouldn't that remove some of the boilerplate? No need for explicitly passing the `url` and `downloadId` to the item itself.

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
> +    private fun onDownloadBackupFileClicked(url: String) {
Warning (⚠️): Consider adding a test for the tracking trigger.

PS: The same apply for the `dismissNoticeClicked(...)` function below.

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
> +        dismissBackupDownloadJob = viewModelScope.launch {
Question (❓): Is canceling the job needed here? Probably not, right? If that is indeed the case I believe this can be updated to the below:
```
viewModelScope.launch { postDismissBackupDownloadUseCase.dismissBackupDownload(downloadId, site) }
reloadEvents(backupDownloadEvent = BackupDownloadEvent(displayNotice = false, displayProgress = false))
```

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
> +    fun onQueryBackupDownloadStatus(rewindId: String, downloadId: Long, actionState: Int) {
Warning (⚠️): Consider adding and updating any tests related to this change.

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
> +        reloadEvents(
Blocker (🚫): By removing this if logic here, the UI will end up scrolling on top every 1 second, while the backup download is in progress and up until it completes.

Why was this removed in the first place?  I understand why the if logic was updated on the `Complete` status scenario, but I believe this is not necessary here, isn't it?

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
>      private fun handleBackupDownloadStatusForComplete(state: BackupDownloadRequestState.Complete) {
Warning (⚠️): Consider adding a test for the new logic added here.

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
> +                displayNotice = isBackupDownloadFileValid(state.url, state.validUntil, state.downloadId),
Suggestion (💡): Maybe this can be moved to the `GetBackupDownloadStatusUseCase` and be tested there as well? Then, this will be passed to the `BackupDownloadRequestState.Complete` state as `isValid`, above the current `validUntil` field?
```
displayNotice = state.isValid,
```

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/res/layout/activity_log_list_notice_item.xml
> +<?xml version="1.0" encoding="utf-8"?>
Minor (🔍): Consider reformatting this file.

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/res/layout/activity_log_list_notice_item.xml
> +        tools:text="We successfully created a backup download file from October 21, 2020 at 3:40 AM."
Suggestion (💡): Since the `android:text` is already set here, I suggest removing the `tools:text` and keep the text from the `android:text` itself. I understand that this text has a couple of params, which can seems weird in the preview, but I still believe that this is better since the `@string` can change in due time and we can have an outdated preview. Actually it is already kind of out of sync.

PS: Same applies for all other places where `tools:text` is used in this file (`Download` and `Dismiss` buttons).

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/res/layout/activity_log_list_notice_item.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
Question (❓): Couldn't the same result be achieved with only one layer of `ConstraintLayout`?

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/main/res/values/styles.xml
> +    <style name="ActivityLogList.Notice.Item.Label" parent="android:Widget.TextView">
Suggestion (💡): I usually suggest that the `layout_width` and `layout_height` to not be part of a style since they are totally dependent on the individual screen and how a specific element is positions in it. Also, I consider the `layout_margin` to be included in this category. However, the `padding` can be indeed considered part of the style.

PS: I see both approached being used on our styles, as such I am okay with anyway you decide to proceed with that. This was just me sharing my thoughts since I would have done it the way I described it.

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/test/java/org/wordpress/android/ui/jetpack/backup/download/usecases/PostDismissBackupDownloadUseCaseTest.kt
> +    private val downloadId = 100L
Minor (🔍): Consider moving that on top, closer to all the other fields.

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/test/java/org/wordpress/android/ui/jetpack/backup/download/usecases/PostDismissBackupDownloadUseCaseTest.kt
> +                        )
Minor (🔍): Consider updating the format of this `whenever/thenReturn` to the blelow:
```
whenever(activityLogStore.dismissBackupDownload(any())).thenReturn(
        OnDismissBackupDownload(
                downloadId, DismissBackupDownloadError(GENERIC_ERROR),
                DISMISS_BACKUP_DOWNLOAD
        )
)
```

PS: The same applies for the test further below.

2021-02-25 16:01 UTC, ParaskP7 commented on WordPress/src/test/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModelTest.kt
> +                .thenReturn(BACKUP_NOTICE)
Minor (🔍): Consider moving that on top, next to the other line, like:
```
).thenReturn(BACKUP_NOTICE)
```

2021-02-25 16:04 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/ui/jetpack/backup/download/BackupDownloadViewModel.kt
> +            val inProgress: Boolean = true
@ParaskP7 I noticed this when cherry picking and removed it already. 👍

2021-02-25 16:16 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
> +    private var currentBackupDownloadEvent = BackupDownloadEvent(false, displayNotice = false)
I caught this one too in the cherry pick

2021-02-25 16:38 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/ui/jetpack/backup/download/usecases/PostDismissBackupDownloadUseCase.kt
> +    private suspend fun handleError(
Good suggestion, incorporated into cherry picked branch. Thanks

2021-02-25 17:02 UTC, zwarm commented on WordPress/src/main/res/values/styles.xml
> +    <style name="ActivityLogList.Notice.Item.Label" parent="android:Widget.TextView">
Going to leave this as is for this PR, as there are multiple approaches to using styles. We should have a follow up on future direction overall. Thanks

2021-02-25 17:54 UTC, zwarm commented on WordPress/src/main/res/layout/activity_log_list_notice_item.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
Going to leave this as is for now, if I have time I will revisit

2021-02-25 18:00 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
> +        dismissBackupDownloadJob = viewModelScope.launch {
Removed in the cherry pick PR

2021-02-25 18:04 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
>          if (backupDownloadEvent.isCompleted) {
Removed as discussed. 🙇

2021-02-25 18:08 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
> +                    primaryActionButtonClickListener = this@ActivityLogViewModel::onDownloadBackupFileClicked,
Updated as discussed

2021-02-25 18:17 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
> +        reloadEvents(
Added back as discussed. Thanks

2021-02-25 18:18 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
> +                displayNotice = isBackupDownloadFileValid(state.url, state.validUntil, state.downloadId),
Moved as discussed

2021-02-25 22:20 UTC, zwarm commented
@ParaskP7  - This PR was closed and replaced with #14155

2021-02-25 22:20 UTC, closed without merging

2021-02-26 08:26 UTC, ParaskP7 commented on WordPress/src/main/res/values/styles.xml
> +    <style name="ActivityLogList.Notice.Item.Label" parent="android:Widget.TextView">
Thanks for considering it @zwarm ! 🌟 

Cc @ashiagr here so that we can setup a quick call on that to first discuss it amongst us. 🙏