Adding liker faces train in reader and allow to access the list of likers
wordpress-mobile/WordPress-Android pull request #14375
Opened 2021-03-31 10:49 UTC by develric

Part of the #14137. This PR shows liker faces (up to 5) in the Reader Post Details and allow to open the list of likers already used in the Nontifications section (see #14361).

## To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-03-31 18:21 UTC, mattmiklic requested changes
@develric This is looking really good. One change to request; let's go from 1dp to 2dp for the white border on each avatar. That might or might not affect the offset you want to use between them, but what you have here (-4dp) looks good right now.

2021-03-31 20:48 UTC, develric commented
Hi @mattmiklic , thanks for the follow up. As we discussed a bit on slack here below the versions with 2dp white border and -4dp spacing (on the left) and -6dp spacing (on the right). If I got it right we both seems to prefer the -6dp, correct? If that's the correct, I will push the code changes accordingly 🙇 

| -4dp spacing | -6dp spacing |
|---|---|
| ![image](https://user-images.githubusercontent.com/47797566/113209268-1f5cc580-9273-11eb-9d14-b2a6bcc5b472.png) | ![image](https://user-images.githubusercontent.com/47797566/113209343-3bf8fd80-9273-11eb-9a54-80b4fb852311.png) |

2021-03-31 20:49 UTC, mattmiklic approved these changes
Everything looks perfect now; thanks!

2021-04-02 23:20 UTC, tw875768 approved these changes

2021-04-08 03:42 UTC, khaykov commented
Sorry, @develric , I didn't get a chance to look at this one today. Will prioritize it for tomorrow!

2021-04-09 00:10 UTC, khaykov approved these changes
Looks and works great, @develric ! I left couple of comments in code.

In addition, I noticed that the Likers are not aligned with post content in landscape mode:
[![Image from Gyazo](https://i.gyazo.com/190c3eee68ffb5359065c34b0a9a3d13.png)](https://gyazo.com/190c3eee68ffb5359065c34b0a9a3d13)

Also, when opening likes activity from the post, you can tap on the first row to open the same post again (and again, etc.). What do you think about closing the likes activity if the post in the first row is the same as the one we navigated from originally? This adds some extra logic, so I'm not sure it's worth it for this pretty edge case.

2021-04-09 00:10 UTC, khaykov commented on WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListActivity.kt
> +        val listScenario = intent.getParcelableExtra<ListScenario>(KEY_LIST_SCENARIO)
Do we want to check if `listScenario` is null here, and do something if it's not there (eg. throw an exception)?

2021-04-09 00:10 UTC, khaykov commented on WordPress/src/main/java/org/wordpress/android/ui/reader/viewholders/PostLikerItemDecorator.kt
> +            outRect.set((outRect.left - leftOffset), outRect.top, outRect.right, outRect.bottom)
I think we need to add a case for for RTL, or it will look like this:
[![Image from Gyazo](https://i.gyazo.com/1adf2b79a9e380e0d15197072db87560.png)](https://gyazo.com/1adf2b79a9e380e0d15197072db87560)

2021-04-09 00:10 UTC, khaykov commented on WordPress/src/main/res/values/strings.xml
> +    <string name="like_title_single_text">1 Like</string>
While the meaning is pretty clear, I think we could change the string name to `like_title_singular`, so it will be easier for translators to get the idea :)

2021-04-09 00:10 UTC, khaykov commented on WordPress/src/main/res/values/strings.xml
> +    <string name="like_title_multiple_text">%d Likes</string>
Similarly, here we could change it to `like_title_plural` (and same for other strings). 

Also, It might be an overkill just for 2 strings, but Android supports plurals natively, so you can have something like this in the strings.xml:

```
<plurals name="like_title">
        <item quantity="one">%d Like</item>
        <item quantity="other">%d Likes</item>
</plurals>
```

And retrieve them with:
`getResources().getQuantityString(R.plurals.like_title, numLikes, numLikes);`

2021-04-09 00:10 UTC, khaykov commented on WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
> +        val isLikeDataChanged = lastRenderedLikesData?.let {
What do you think about adding a method to `RenderedLikesData` that will do this comparison? Something like `isSameAsInPost()` or `isMatchingThePost()`, or something like this. This way we can test it too :)

2021-04-13 15:29 UTC, develric commented
Hey @khaykov 👋 ! Thanks for the review and advices 🙇 ! I think you already checked that with the feature flag off, the behaviour in the reader details is correct (that is not train of faces and every element is in it's location with the expected content). If it is the case, I would merge this one (since we are not removing the feature flag on this PR) and address your suggestions in a dedicated PR, so that it is more manageable hopefully. Let me know wdyt, thanks sir 🙇 !

2021-04-13 16:45 UTC, khaykov approved these changes
Sure, sounds like a good plan. I made sure the feature flag is working as intended and going to merge this one 👍

2021-04-13 16:46 UTC, merged