Remove synthetic accessors: Site Creation
wordpress-mobile/WordPress-Android pull request #14871
Opened 2021-06-18 18:56 UTC by zwarm

Parent #14845 

This PR replaces synthetic accessors within two steps of the SiteCreation flow.

Details
- SiteCreationBaseFormFragment
	- Converted from java to kotlin
	- View binding takes place view in `onViewCreated`, so need to set a `binding` field
	- Added abstract fun`setBindingViewStubListener` to enable subclasses to inflate their own layout
	- Replace synthetic accessors with view binding

- SiteCreationDomainsFragment
	- Replaced synthetic accessors with view binding
	- Implemented `setBindingViewStubListener` to inflate layout into ViewStub

- SiteCreationPreviewFragment
	- Replaced synthetic accessors with view binding
	- Implemented `setBindingViewStubListener` to inflate layout into ViewStub
	- Nix animation when any required param is null (a.k.a. - happens if view binding are null)

- Layout files
	- Added `@+id\` to all includes
	- Extracted out layout-land `site_creation_preivew_screen` into layout-land `site_creation_preivew_screen_default` to match portrait/h480dp layouts. This enforces that we access the same `binding` fields throughout `SiteCreationPreviewFragment`

To Test
- Launch the app
- Make sure the device is using Portrait configuration
- Navigate to MySites 
- Choose the site selector to open the Sites List View
- Tap the + in the upper right hand corner
- Tap Create WordPress.com site
- Select a template (doesn't matter) and tap the Choose button
- (1) Note the Choose a domain view is shown
- (2) Test that the search feature is performing as expected
- Select a domain name and tap Create Site
- (3) Note the progress view is shown
- (4) Note the progress view transitions to a preview view once the site is created

- Repeat the test for Landscape configuration (the PixelC emulator works great)
## Regression Notes
1. Potential unintended areas of impact
Site Creation flow

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual tested the site creation flow

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-06-21 14:52 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SiteCreationPreviewFragment.kt
> +    private lateinit var binding: SiteCreationPreviewScreenBinding
By using lateinit var, the need for setting to null is removed. Subsequent binding get() also drop the null requirement. This trickles down to using the fields in the code base.

2021-06-22 12:04 UTC, ParaskP7 requested changes
👋 @zwarm !

I have reviewed and tested this PR as per the instructions, everything works as expected, amazing job! 🌟 🌟 🌟 

I have left one warning (⚠️) comment, some questions (❓), few suggestions (💡) and a couple of minor (🔍) comments for you to consider. I am **NOT** going to approve this PR, since I want to make sure that I am not missing anything on the warning (⚠️) comment I left.

PS: I had a difficult time reviewing this PR and it took me more time that I would have liked spending on it. Also, I am not confident that I did the best I could as there were a lot of changes that I couldn't follow with ease. I can only suggest the below going forward:
- Don't mix commits. For example, prefer to separate the reordering of the methods of a class first and then applying any additional refactoring. As such, instead of creating a single commit out of those two separate steps, prefer to create two commits. This way the reviewers that are reviewing those changes can choose to review commit-by-commit if they find it difficult to review otherwise.
- Buildable commits. Every commit should be able to build and compile by its own. We are sometimes tempted to selected commits out of a bigger set of changes that we already did. But, if we are not careful enough, selecting, for example 2/3 files to commit, just to create a separate commit, this might mean that the remaining 1/3 file can end up being broken. Or, the already committed 2/3 files might be missing code that is dependent from this uncommitted 1/3 file. When a reviewer then reviews this first commit, it will be hard for them to connect the dots unless they review the next one, of the whole change set, thinking false positively, that there is a breaking change with that commit.

2021-06-22 12:04 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
> +    private lateinit var binding: SiteCreationDomainsScreenBinding
Warning (⚠️): Unless I am missing something, isn't the `lateinit` pattern to be used on `Activities` only, and instead, for `Fragments`, we should be using a nullable `binding`? Also, the `onDestroyView()` should be added back and utilised to nullify the `binding` afterwards, is it not?

PS: The same applies for the sibling `SiteCreationPreviewFragment` and parent `SiteCreationBaseFormFragment` fragments.

2021-06-22 12:04 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
> +                initViewModel()
Minor (🔍): Consider reformatting the `initRecyclerView()` and `initViewModel()` function usages to correct indent.

2021-06-22 12:04 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
>      private fun updateContentUiState(contentState: DomainsUiContentState) {
Suggestion (💡): Consider making the `updateContentUiState(...)` function an extension of `SiteCreationDomainsScreenBinding` in order to remove the need for the `with(binding) { ... }` layer.

2021-06-22 12:04 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SiteCreationPreviewFragment.kt
> +    override fun setupContent() {
Suggestion (💡): Consider utilising extension functions with all these view bindings to remove some extra layering and boilerplate. For example:

```
    override fun setupContent() {
        siteCreationPreviewScreenDefaultBinding.initViewModel()
        fullscreenErrorWithRetryBinding.initRetryButton()
        siteCreationPreviewScreenDefaultBinding.initOkButton()
        fullscreenErrorWithRetryBinding.initCancelWizardButton()
        fullscreenErrorWithRetryBinding.initContactSupportButton()
    }

    private fun SiteCreationPreviewScreenDefaultBinding.initViewModel() {
        viewModel = ViewModelProvider(this@SiteCreationPreviewFragment, viewModelFactory)
                .get(SitePreviewViewModel::class.java)
        viewModel.uiState.observe(this@SiteCreationPreviewFragment, { uiState ->
            uiState?.let {
                when (uiState) {
                    is SitePreviewContentUiState -> updateContentLayout(uiState.data)
                    is SitePreviewWebErrorUiState -> updateContentLayout(uiState.data)
                    is SitePreviewLoadingShimmerState -> updateContentLayout(uiState.data)
                    is SitePreviewFullscreenProgressUiState ->
                        siteCreationProgressCreatingSiteBinding.updateLoadingLayout(uiState)
                    is SitePreviewFullscreenErrorUiState ->
                        fullscreenErrorWithRetryBinding.updateErrorLayout(uiState)
                }
                ...

            }
        })
```

The above is just one of those things you can do to make the code a bit more straightforward. Then the functions could end up looking like:

```
    private fun FullscreenErrorWithRetryBinding.initRetryButton() {
        errorRetry.setOnClickListener { viewModel.retry() }
    }

    private fun SiteCreationPreviewScreenDefaultBinding.initOkButton() {
        okButton.setOnClickListener { viewModel.onOkButtonClicked() }
    }

    private fun FullscreenErrorWithRetryBinding.initCancelWizardButton() {
        cancelWizardButton.setOnClickListener { viewModel.onCancelWizardClicked() }
    }

    private fun FullscreenErrorWithRetryBinding.initContactSupportButton() {
        contactSupport.setOnClickListener { viewModel.onHelpClicked() }
    }

    private fun SiteCreationPreviewScreenDefaultBinding.updateContentLayout(sitePreviewData: SitePreviewData) {
        sitePreviewData.apply {
            siteCreationPreviewWebViewContainerBinding.sitePreviewWebUrlTitle.text = createSpannableUrl(
                    requireNotNull(activity),
                    shortUrl,
                    subDomainIndices,
                    domainIndices
            )
        }
        if (contentLayout.visibility == View.GONE) {
            animateContentTransition()
            view?.announceForAccessibility(
                    getString(R.string.new_site_creation_preview_title) +
                            getString(R.string.new_site_creation_site_preview_content_description)
            )
        }
    }
```

Note that my suggestion makes the assumption that the main view binding to be used is the `SiteCreationPreviewScreenDefaultBinding`. That is especially necessary when you would need to choose between two of them. Since the rest are children of that main view binding, it seems like a reasonable choice. Wdyt?

This refactor will help removing the need to use `with(xyzBinding) { ... }` from almost everywhere, thus making the code look more simpler.

2021-06-22 12:04 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SiteCreationPreviewFragment.kt
> -    override fun onActivityCreated(savedInstanceState: Bundle?) {
Question (❓): Why was this `onActivityCreated(...)` override function remove altogether?

PS: I am probably missing other functions like that, which got removed in the process. Please let me know if you can think of others like that. This is due to the fact that it was hard for me to review the changes and although I tried my best I am not comfortable that I didn't miss anything.

2021-06-22 12:04 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationBaseFormFragment.kt
> +abstract class SiteCreationBaseFormFragment : Fragment(R.layout.site_creation_form_screen) {
Suggestion (💡): When converting code from Java to Kotlin the diff is usually helping because the IDE can't understand that those 2 files are the same. Thus, reviewing this change becomes very tricky. What I usually suggest and doing myself if the below pattern to help others review this conversion, it is a simple two-stage approach:
- Rename the extension of the to-be-converted file, from `.java` to `.kt`, and **commit** the renamed `.kt` file.
- Rename it back, from `.kt` to `.java`, apply the automatic conversion, and **commit** the converted `.kt` file.

Let me know of the above and I can help you with guiding on the above process. Actually, someone already created a plugin for that, but I am not sure that this plugin is already compatible with Android Studio at this time. Will double check that asap.

2021-06-22 12:16 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationBaseFormFragment.kt
> +abstract class SiteCreationBaseFormFragment : Fragment(R.layout.site_creation_form_screen) {
Sure, for next time. Thanks

2021-06-22 12:20 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
> +    private lateinit var binding: SiteCreationDomainsScreenBinding
Yeah, I was on the fence on this one. It works as expected, but 🤔  I wonder if it should be used

2021-06-22 12:22 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SiteCreationPreviewFragment.kt
> +    override fun setupContent() {
I didn't because there are instances where you'd need more than 1 binding for the method.

2021-06-22 12:34 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
>      private fun updateContentUiState(contentState: DomainsUiContentState) {
With the change to using a nullable again, references to binding has to use a ?.

2021-06-22 12:35 UTC, zwarm commented
@ParaskP7 

Thank you for the feedback. I'll consider this for the future.

2021-06-22 12:42 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
> +    private lateinit var binding: SiteCreationDomainsScreenBinding
SiteCreationDomainsFragment converted back in 0fc0285

2021-06-22 12:42 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
> +                initViewModel()
in e52ad66

2021-06-22 12:42 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
>      private fun updateContentUiState(contentState: DomainsUiContentState) {
in e52ad66

2021-06-22 12:44 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
> +    private lateinit var binding: SiteCreationDomainsScreenBinding
`SiteCreationBaseFormFragment` doesn't use a field pattern, so no changes needed there. Uses (with) in onViewCreated.

2021-06-22 12:57 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
> +    private lateinit var binding: SiteCreationDomainsScreenBinding
`SiteCreationPreviewFragment` reverted back in f7369e1

2021-06-22 13:00 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SiteCreationPreviewFragment.kt
> -    override fun onActivityCreated(savedInstanceState: Bundle?) {
It's back in d8f9e75. I think it was inadvertently removed while moving methods.

2021-06-22 14:03 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SiteCreationPreviewFragment.kt
> +    override fun setupContent() {
In 110f879

2021-06-22 14:07 UTC, ParaskP7 commented on WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SiteCreationPreviewFragment.kt
> +    override fun setupContent() {
As discussed, this is now done here: 110f8797dae11bd567e35ea4cea04e9309b52d46

2021-06-22 14:27 UTC, ParaskP7 approved these changes
👋 @zwarm !

Thanks for all your changes, everything LGTM!

2021-06-22 14:46 UTC, merged