My Site Dashboard: Phase 1 - Quick Actions
wordpress-mobile/WordPress-Android pull request #15243
Opened 2021-08-25 20:47 UTC by zwarm

Parent #15193

This PR includes
- UI changes according to the latest zeplin design docs (margins/paddings, font size, card border, button border)
- Rename `quick_start_toolbar` to `my_site_card_toolbar`
- Added a new layout file for the quick actions called `my_site_quick_actions_card`. This is the wrapper and includes the existing `quick_actions_block` layout file and the `my_site_card_toolbar`. Perhaps we **should** revisit names?
- Extracted the building of QuickActionsBlock to it's own builder `QuickActionsBlockBuilder` + associated tests in `QuickActionsBlockBuilderTest`.
- Updated unit tests in `MySiteViewModelTest`

Dark | Light
-- | --
<img width="250" height="500" alt="Alt desc" src="https://user-images.githubusercontent.com/506707/130860294-f9b6d733-e102-4400-95d0-2e67bd2a9a96.png"> | <img width="250" height="500" alt="Alt desc" src="https://user-images.githubusercontent.com/506707/130860301-83e6261d-93ce-468a-97f8-5748d26ebe88.png">

**To test:**

**Test Quick Actions Clicks are functional**
- Launch the app 
- Navigate to My Site -> App Settings -> Test feature configuration
- Enable the `MySiteImprovementsFeatureConfig` and tap the button to restart the app 
- Navigate to the My Site tab
- Tap on all the quick starts button to ensure they are working correctly

**Test that Pages doesn't show in quick actions**
- Navigate to My Site
- Using the site selector, select a site that you don't have edit capability for
- On the My Site tab, the quick actions card should not show the Pages action

**Test that Pages action shows blue focus icon**
- Navigate to My Site
- Using the site selector, select a site that Quick Tasks are enabled
- Tap on the Customize Your Site to launch the dialog
- Tap on Review Site Pages
- Note that the Pages quick action button shows the flashing blue focus point.
 
**Test that Pages action shows blue focus icon**
- Navigate to My Site
- Using the site selector, select a site that Quick Tasks are enabled
- Tap on the Grow your audience to launch the dialog
- Tap on Check your stats
- Note that the Stats quick action button shows the flashing blue focus point.

**Note**
Make toolbar "More" invisible - this part will be handled separately.

## Regression Notes
1. Potential unintended areas of impact
Quick Actions navigation does not work

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
`MySiteViewModelTest` and `QuickActionsBlockBuilderTest`

PR submission checklist:

- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-08-26 06:42 UTC, ashiagr approved these changes
Great job @zwarm! 🤩 
As hiding more menu is a separate sub-task, we're good to merge this PR. Will wait for approval from Chris.

2021-08-26 11:50 UTC, osullivanchris requested changes
Really nice to see this, it looks great! Just one small tweak. The space below the Quick Actions looks a bit larger than the mock. 

<img width="1745" alt="Screenshot 2021-08-26 at 12 48 46" src="https://user-images.githubusercontent.com/50576199/130957911-d23296d1-8e41-4fe8-95dc-04e92d4559c1.png">


I'm measuring it at 35dp but I'm guessing its actually 32dp either in one chunk or maybe there's 24 defined + 8 coming from within the Quick Actions component.

Could we reduce the space by 8dp there?

2021-08-26 11:52 UTC, osullivanchris commented
I have also internally requested a user facing name for this feature in the comments at p2JRYi-5sv-p2

2021-08-26 12:13 UTC, ashiagr commented
> Could we reduce the space by `8dp` there?

Reduced in a4eeab2b38cc54bc2373c059d8545264419ddd56. Chris can you take another look?

Before | After
-------|------
![device-2021-08-26-173246](https://user-images.githubusercontent.com/1405144/130961436-62f5d84e-8264-47df-803c-56fce0f548f3.png) | ![device-2021-08-26-173205](https://user-images.githubusercontent.com/1405144/130961425-2e1354cd-47a8-4df2-b381-ffd2a989cca1.png) 



> I have also internally requested a user facing name for this feature

👍

2021-08-26 13:42 UTC, osullivanchris approved these changes
> Reduced in a4eeab2. Chris can you take another look?

Thanks @ashiagr. Seeing that it was 40->32 I actually think we can shave a little further and remove another 8dp making it 24dp if thats ok? Sorry to get you to make the same fix again. I think then it will be perfectly balanced.

I also noticed one other thing. When one of the actions is pressed, it displays a shadow like we had before. Could it instead have the grey ripple/overlay touch effect that we use on rows and most places?

![Screenshot_2021-08-26-14-36-06-245_org wordpress android prealpha](https://user-images.githubusercontent.com/50576199/130973362-e114dec3-daa5-44bd-b6a2-56f1f4dc31f0.jpg)


I am hitting approve on this one because the details are minor, so you can merge before waiting for me to review again.

2021-08-27 05:07 UTC, ashiagr commented
> Seeing that it was 40->32 I actually think we can shave a little further and remove another 8dp making it 24dp

You're right, it feels perfect by reducing by another 8dp. Reduced in 5def07f.

> I also noticed one other thing. When one of the actions is pressed, it displays a shadow like we had before. Could it instead have the grey ripple/overlay touch effect that we use on rows and most places?

Added in fa89508. It looks better indeed 🙌.

https://user-images.githubusercontent.com/1405144/131074733-d87ba8f8-f76a-45fd-950c-53fdcb8f1fa6.mov

2021-08-27 07:50 UTC, osullivanchris commented
> You're right, it feels perfect by reducing by another 8dp. Reduced in 5def07f.

🙌  great, glad you agree too!

> Added in fa89508. It looks better indeed 🙌.

It definitely looks better. But I'm now seeing the grey I expected *and* the shadow is still there. Is it possible to remove the shadow? I believe these buttons were originally derived from Floating Action Buttons IIRC, so that could be causing the trouble 😄

2021-08-27 08:39 UTC, ashiagr commented
> I expected and the shadow is still there

I see, hope commit 9403a6f resolves it 😄🤞 

https://user-images.githubusercontent.com/1405144/131098873-f2ff8c69-e747-4c76-9ce5-d5fe984e1ff7.mov

2021-08-27 12:36 UTC, osullivanchris commented
> I see, hope commit 9403a6f resolves it 😄🤞

That's perfect. Thanks for resolving these little details @ashiagr !

2021-08-27 13:12 UTC, merged

2021-08-28 13:32 UTC, zwarm commented
Thanks @ashiagr for addressing @osullivanchris feedback while I was AFK. 👍

2021-08-29 12:28 UTC, PACE210 commented on WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
> -        quickStartMore.setOnClickListener { showQuickStartCardMenu() }
False
Stop

2021-08-29 12:28 UTC, PACE210 commented on WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
> -        quickStartMore.setOnClickListener { showQuickStartCardMenu() }
False
Stop