[Tooling] Install drawText when running promo-screenshots job
wordpress-mobile/WordPress-Android pull request #15981
Opened 2022-02-18 17:45 UTC by AliSoftware

Since `drawText` is not part of `release-toolkit` since the release of `3.0.0`.

See also https://github.com/wordpress-mobile/WordPress-Android/pull/15963

---

### To test…?

Not sure if that will be easy to test (I mean, the right way would be to actually run the whole screenshot suite from A to Z so that it goes thru promo-screenshots… but do we really have the courage to go thru this, especially since I'm not even sure that job and the associated UI tests targets have been kept up-to-date…)

2022-02-18 17:46 UTC, AliSoftware commented on .circleci/config.yml
> +      xcode: 13.2.1
When I tried to `brew install automattic/build-tools/drawText` on my Mac, it failed because I didn't have Xcode 13.2.1:

```
 $ brew install automattic/build-tools/drawText 

Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Downloading https://github.com/Automattic/drawText/releases/download/0.1/drawText.tar.gz
Already downloaded: /Users/olivier/Library/Caches/Homebrew/downloads/148493bbd7df5c28cf2b437167803d49daa9e8e8ce7986540d4558ae663702df--drawText.tar.gz
==> Installing drawtext from automattic/build-tools
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.2.1.
```

I had Xcode `13.1` and `13.2` on my machine at that time… (and `xcode-select --install` told me that CLT for 13.2 were already installed, and `softwareupdate --all --list` didn't list any update), but did not have Xcode `13.2.1` (downloading it as we speak…).

Hence me having to update that CircleCI image to use Xcode 13.2.1 here too, since it seems to be a requirement for the `drawText` homebrew formula.

2022-02-22 01:31 UTC, mokagio requested changes
I hacked the workflow to run only the brew step [here](https://github.com/wordpress-mobile/WordPress-Android/pull/15987/commits/9bd24da9f38e7c5b1de2330cf18f729a4e8e0129).

[It worked](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-Android/29134/workflows/10016bc6-7d1b-41bb-bebd-a335dceb88ec/jobs/119157)

![image](https://user-images.githubusercontent.com/1218433/155046534-096687cc-bce3-4c7d-98f5-2056f90a1552.png)

However, by changing the agent we now can't leverage the `working_directory: /tmp/workspace` and `persist_to_workspace` features to shared files between the `raw-screenshots` and `promo-screenshots` steps.

This can be seen in the error messages reported in other steps in the job:

```
error computing cache key: template: cacheKey:1:23: executing "cacheKey" at <checksum "Gemfile.lock">: error calling checksum: open /tmp/workspace/Gemfile.lock: no such file or directory
```

I think we could get the `Gemfile` and `Gemfile.lock` by checking out the repo, then use S3 to store the raw screenshots from the step before. 

But, at this point I wonder if it's best to wait for Buildkite?

(_Requesting changes to avoid accidental merges in the future_)

2022-02-22 01:40 UTC, AliSoftware commented
Thanks for taking the time to test this in details!

I believe though that the failure you mention about Gemfile.lock not being found is precisely because of your hack though? Especially since you removed the dependency between promo-screenshots requiring raw-screenshots, that explains why the raw-screenshots job didn't run and since that's the one doing the checkout and persisting the Gemfile.lock, no wonder it failed to find it if you didn't make that job run as a dependency anymore… no?

2022-02-22 04:41 UTC, mokagio approved these changes
> However, by changing the agent we now can't leverage the `working_directory: /tmp/workspace` and `persist_to_workspace` features to shared files between the raw-screenshots and promo-screenshots steps.

I was under the impression that the workspace required the same kind of `executor`, but that's not the case and I was wrong.

I restored the `raw-screenshot` step (a streamlined version of it) and the workspace persistance [worked](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-Android/29135/workflows/b2232c31-695d-453f-b62d-e7341b1d41e7/jobs/119160) and let the pipeline finish.

:shipit:

2022-02-22 10:30 UTC, AliSoftware commented
> I was under the impression that the workspace required the same kind of `executor`, but that's not the case and I was wrong.

Nah that's actually the other way around 😛 

Because we use different executors (an Android Docker image for generating the raw screenshots, a Mac machine to run `drawText` and assemble promo screenshots), those 2 different executors have a different typical filesystem hierarchy (Linux vs Mac) and thus different default working directories.
So without the `working_dir: …` instruction, each job, using a different executor type, would have different working dirs and the restoration of the workspace would fail. And the solution was to enforce the `working_dir` to be the same in both jobs regardless of Linux vs Mac so that the restoration step could work despite them being different OSes/executors.

PS: Note that even before this PR, the executor for `promo-screenshots` was _already_ a Mac machine, so we already had the case of Linux (`raw-screenshots`) vs Mac (`promo-screenhots`) environments; the only thing I changed is the version of Xcode on the Mac machine, but it was already a Mac machine before, so that shouldn't affect the `workspace_dir` trick necessity 🙃

2022-02-22 10:31 UTC, merged