Changes: The tab title to Menu from Site Menu
wordpress-mobile/WordPress-Android pull request #16307
Opened 2022-04-12 14:03 UTC by AjeshRPai

Fixes #16305 

This PR changes the title of the tab from `Site menu` to `Menu` as per [this reference](pbArwn-4jn). 

![Uploading Screenshot_20220412_192436.png…]()

To test:

Test 1 
- Go to My Site 
- Notice that the title of the tabs are `Home` and `Menu` 

Test 2
- Go to My Site -> App Settings -> Initial Screen 
- Notice the selections are `Home` and `Menu`

Test 3 
- Go to My Site screen with a Site having Quick Start in Progress 
- Set Initial screen as Home 
- Start any quick start(Visit Site, Explore Plans or Post Sharing) which has focus point in `MENU`
- Notice that the snackbar prompt says to click at the `MENU` tab

## Regression Notes
1. Potential unintended areas of impact
Tab title is not shown properly in 
- Initial screen settings 
- Quick start snack bar prompt 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing 

3. What automated tests I added (or what prevented me from doing so)
none 

PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-04-12 14:48 UTC, zwarm requested changes
👋  @AjeshRPai - The tab names look great, as does the App Settings -> Initial Screen selection view screen; however there seems to be a mismatch between "site menu" and "menu" in the label. When "menu" is the default, it is not showing properly as the label in the App Settings view. This was the same issue I encountered because "dashboard" and "home" do not match.

Pre-req: Have to be in a situation where the "home" tab is assigned by the experiment.
- Fresh install
- Login
- Select site
- Navigate to Me -> App Settings
- Note that the Initial Screen setting does not have a value. 
- <img width="250" height="500" alt="Alt desc" src="https://user-images.githubusercontent.com/506707/162989215-80c775e6-e451-4a8f-9f73-15518e49e98d.png">

2022-04-13 07:59 UTC, AjeshRPai commented
@zwarm Great catch, Thanks for pointing it out and letting me know how to reproduce it. I believe I have made the necessary changes in the commit [60a71ef](https://github.com/wordpress-mobile/WordPress-Android/pull/16307/commits/60a71efeb01917c8faa42113812e563d9eefc28b). I have tested the scenario where the `Menu` tab is assigned by the experiment. 

![Screenshot_20220413_131338](https://user-images.githubusercontent.com/17463767/163128554-b12c57b9-a4c5-4c28-be78-e93211f2a323.png)

2022-04-13 13:19 UTC, zwarm requested changes
Hi @AjeshRPai . The issue with App Settings look good, but now there is an issue selecting the "menu" tab. 

Steps to reproduce
- Navigate to Me -> App Settings
- Set initial screen to "menu"
- Close the app (swipe it away)
- Open the app
- "Menu" should be the default tab, but "home" is selected instead

Take a look in MySiteViewModel ... The initial screen value = "menu" which doesn't == "site_menu".  
```
private val defaultABExperimentTab: MySiteTabType
        get() = if (isMySiteTabsEnabled) {
           if (appPrefsWrapper.getMySiteInitialScreen() == MySiteTabType.SITE_MENU.label) {
                MySiteTabType.SITE_MENU
            } else {
                MySiteTabType.DASHBOARD
            }
        } else {
            MySiteTabType.ALL
        }
```

2022-04-13 18:52 UTC, AjeshRPai commented
@zwarm Yup, Right. How did I miss that? 😓 . I have done the changes again in the commit [2757860](https://github.com/wordpress-mobile/WordPress-Android/pull/16307/commits/27578600929ce84deede4b5e21a8ed8152c9a0f7) and tested the following scenario. It works as expected. 

- Navigate to Me -> App Settings
- Set initial screen to "menu"
- Close the app (swipe it away)
- Open the app
- 🟢 "Menu" should be the default tab

I hope that I haven't missed any other scenarios now. 🤞🏼 . Please have a look at the changes.

2022-04-14 10:45 UTC, ashiagr commented
Hey @zwarm! 

As @AjeshRPai is on leave till the end of this week, I took over this PR to fix failing tests.

I tested it t to see if everything was working when I noticed an issue with changing the initial screen preference: the initial screen preference value was compared with the site menu variant tracking label which are different values now (80c187a5ad51b11913aab22cf3ff3adf56aec963). In order to fix it, I refactored `AppPrefs.setInitialScreenFromMySiteDefaultTabExperimentVariant()` with details in the commit message. I hope I understood the function's purpose correctly 🤞 else let's sync to get this right. 

I also eliminated a few constants (`VARIANT_DASHBOARD`, `VARIANT_DASHBOARD`, `VARIANT_HOME`, `VARIANT_MENU`, `home`, `menu`) at different places in commits ([95b1dfd](https://github.com/wordpress-mobile/WordPress-Android/pull/16307/commits/95b1dfdc923b5d7588c727302a21779d4e1d68a3) ... [47dca0a](https://github.com/wordpress-mobile/WordPress-Android/pull/16307/commits/47dca0a303502572538ecf64349f64c67bb8a739)). If you feel these are too many changes, I can revert them. 😅 

Thanks so much for your time on this. 🙏

2022-04-14 13:57 UTC, zwarm approved these changes
@ashiagr - All works as expected with the changes you made. The correct "tracking label" is used for tracking. The initial screen value is updated properly and the app setting is correct. And the tabs names look great!!
Thanks for getting this one over the finish line. 
🎉

2022-04-14 13:57 UTC, merged