Stats revamp v2 latest post summary card
wordpress-mobile/WordPress-Android pull request #16443
Opened 2022-04-29 05:32 UTC by ravishanker

This PR updates Latest Post Summary card to new design as shown below
- Adds Latest Post with featured image (if set)
- Displays stats in three columns (and removes graph)

TODO:
- [ ] [Corresponding FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2373) needs to be merged before merging this

Fixes #16424

| Current | New Design | Dark Theme |
|---|---|---|
|![Screenshot_20220429_151424](https://user-images.githubusercontent.com/990349/165888982-5503976d-5420-41f4-b077-88ca9cf78417.png)|![Screenshot_20220429_151749](https://user-images.githubusercontent.com/990349/165889003-ee4b2b7c-cbdc-419c-a8fd-4a17ed448648.png)|![Screenshot_20220429_151809](https://user-images.githubusercontent.com/990349/165889007-d569040c-58c2-4366-9f41-bfe3282a7926.png) |

To test:

Setup:

- Go to App Settings (Tap on Avatar at the top right hand corner on My Site -> Find App Settings)
- Select Debug Settings
- Find StatsRevampV2FeatureConfig under Features in development enable it and restart app

Test 1:

- Launch app
- Go to stats either using quick links or menu
- Ensure that it opens in Insights tab otherwise switch to Insights tab
- Verify that the new Latest Post Summary card is visible and matches the new designs above
- Ensure that featured image is displayed (if a feature image is set)
- View More on the top right corner is visible if there's any data on Views, Likes or Comments
- If data is not available it will display a Share action or Create Post if no latest post as before
- _If the Latest Post Summary card is not present.  Go to stats management (either through ⚙️ menu at the top right hand corner or Add new stats card at the bottom) and add the card and save then return to Insights._

Test 2:

- Turn on the dark theme on your device
- Check the card is displayed as in third image above

Test 3:

- Disable StatsRevampV2FeatureConfig and restart app
- Return to Stats and make sure Most Popular Time card is displayed as in first image above as before.

## Regression Notes
1. Potential unintended areas of impact
None.  Only existing Latest Post Summary card will be updated to new design with additions of a featured image

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
Updated unit tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-04-30 13:10 UTC, irfano requested changes

2022-04-30 13:10 UTC, irfano commented on WordPress/src/main/res/layout/stats_quick_scan_item.xml
> +            tools:text="1"/>
I see you added a third column to `stats_quick_scan_item.xml`. That's a good way to use this layout with the old and new designs. But there are some differences between the old layout and the new design in Figma:
- In the new design, the whole layout has 90dp end margin.
- Value text size is 24sp in the old design and 34sp in the new design.

How can we handle this? Maybe a new layout for stats revamp v2 could be a better solution.

![image](https://user-images.githubusercontent.com/2471769/165997166-40506b9e-0611-41c4-9c12-b5f29f4801ce.png)

2022-04-30 13:10 UTC, irfano commented on WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryMapper.kt
> +            return ListItemWithImage(title = resourceProvider.getString(string.stats_insights_latest_post_empty))
We can use only text for the empty card, without the image gap.

|PR version|Figma version|
|-|-|
|![image](https://user-images.githubusercontent.com/2471769/166006239-94e8d602-f226-4673-93d6-63bd2297583d.png)|![image](https://user-images.githubusercontent.com/2471769/166005988-d03dc345-50ce-46e0-afda-fc88daccd666.png)|

2022-04-30 13:10 UTC, irfano commented on WordPress/src/main/res/layout/stats_block_title_with_more_item.xml
> +        style="@style/StatsBlockTitle"
It looks like the text size is `20sp` in the design, but  `16sp` in the `StatsBlockTitle`. I think we can use a different style for Stats Revamp v2.
We can do this in another PR.

2022-05-02 08:28 UTC, ravishanker commented on WordPress/src/main/res/layout/stats_quick_scan_item.xml
> +            tools:text="1"/>
added margin.  thank you

2022-05-02 08:29 UTC, ravishanker commented on WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryMapper.kt
> +            return ListItemWithImage(title = resourceProvider.getString(string.stats_insights_latest_post_empty))
Good point, was going to do as part empty states.  Fixed it anyhow by hiding image when empty

2022-05-02 08:30 UTC, ravishanker commented on WordPress/src/main/res/layout/stats_block_title_with_more_item.xml
> +        style="@style/StatsBlockTitle"
Yes, we can do this as part styles pr

2022-05-02 09:42 UTC, AliSoftware commented
I'm doing 19.8 code freeze today, so migrating this PR's milestone to 19.9.

(PS: Please ping me to let me know if you _really_ needed this in 19.8, as this would need a rebase that would impact release notes, CfT, and beta wrangling)

2022-05-02 12:03 UTC, irfano commented
I've merged the corresponding [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2373) before this PR. That caused failing unit tests because of the new parameter, `featuredImageUrl`.
A fix is added to the `release/19.8` branch in this [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/16455).

2022-05-02 13:44 UTC, irfano commented on WordPress/src/main/res/layout/stats_quick_scan_item.xml
> +            tools:text="1"/>
Now we have a new problem. :sweat_smile:

![Screenshot_20220502_163541](https://user-images.githubusercontent.com/2471769/166243463-c65265c9-fd67-4384-b085-47bc35352f84.png)

2022-05-02 13:58 UTC, irfano requested changes
Now we have a new problem. 😅

![Screenshot_20220502_163541](https://user-images.githubusercontent.com/2471769/166246194-6e396cde-2cf3-4ed6-9e2f-1461bfd84965.png)

2022-05-03 05:37 UTC, ravishanker commented
> Now we have a new problem. 😅
> 
> ![Screenshot_20220502_163541](https://user-images.githubusercontent.com/2471769/166246194-6e396cde-2cf3-4ed6-9e2f-1461bfd84965.png)

🥹  Looks like there's a mistake in the design actually.  If you look at [iOS designs and their implementation](https://github.com/wordpress-mobile/WordPress-iOS/pull/18476), there's no padding at the end.  Also, adding a padding is causing issues with other languages

2022-05-03 09:16 UTC, irfano approved these changes
> 🥹 Looks like there's a mistake in the design actually. If you look at [iOS designs and their implementation](https://github.com/wordpress-mobile/WordPress-iOS/pull/18476), there's no padding at the end. Also, adding a padding is causing issues with other languages

Oh! That's right! Now I also checked Figma file, it must be a design mistake.
Approved, LGTM! 👍🏻

2022-05-03 09:17 UTC, merged