Quick start for existing users V2 - Changes to tour completion
wordpress-mobile/WordPress-Android pull request #16505
Opened 2022-05-09 20:15 UTC by AjeshRPai

Fixes #16352 

To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-05-10 11:51 UTC, osullivanchris requested changes
@AjeshRPai Hey I installed this build but I haven't been able to complete the tour. For every site it keeps asking me to Explore Plans. But then there is no Plans option in the list to tap. Its happening both for a self hosted site and a dotcom site.

Otherwise the attached video looks good with 1 other issue: the text is flipped in the video. It should be

**Congrats! You know your way around.** Doesn't it feel good to cross things off a list?

At the moment in your video the two sentences are flipped. They look correct in the image you put at the top.

2022-05-10 17:01 UTC, AjeshRPai commented
@osullivanchris Thanks for testing the changes, As you pointed out the issues 

>For every site it keeps asking me to Explore Plans. But then there is no Plans option in the list to tap. Its happening both for a self hosted site and a dotcom site

This is a known issue, the only workaround, for now, is to skip the Explore plans task and complete the quick start tour. The attached video shows how to do that. I have also linked the issue which describes the explore plans bug. 

>Otherwise the attached video looks good with 1 other issue: the text is flipped in the video. It should be

It was an Incorrect Video, I have replaced it with the correct one

2022-05-10 17:18 UTC, leandroalonso commented
> For every site it keeps asking me to Explore Plans. But then there is no Plans option in the list to tap. Its happening both for a self hosted site and a dotcom site

@AjeshRPai @ashiagr I know this is not related to our changes in this project, but can't we simply remove the "Explore Plans" task while Plans isn't visible?

2022-05-11 04:52 UTC, ashiagr commented
👋 @leandroalonso 

Actually, we're thinking about whether we should remove the plan quick start task or update `/plans/mobile` endpoint to return correct plans and re-enable plans. As mentioned here (p1651688458935559/1651587009.445519-slack-C011BKNU1V5), removing a quick start task might not be straightforward. 

@AjeshRPai can you time-box and check how much effort it can take?

2022-05-11 12:09 UTC, AjeshRPai commented
@leandroalonso 

I believe an effort of 3-4 days is needed for removing the plans entirely and since it’s temporary, we will need to make some effort while re-introducing it with new pricing. So I believe reintroducing plans and showing the URL(https://wordpress.com/pricing/) in a Webview is better for now. 

In future, we can take up the task of updating the endpoint  `/plans/mobile` at a later stage once we have the bandwidth. Let me know your thoughts. 

cc: @ashiagr

2022-05-11 12:39 UTC, osullivanchris approved these changes
> This is a known issue, the only workaround, for now, is to skip the Explore plans task and complete the quick start tour. The attached video shows how to do that. I have also linked the Explore plans as a known issue in the PR description

Got it!

> It was an Incorrect Video, I have replaced it with the correct one

Looks better now! Approving but could you also just double check the padding/line spacing is the same on that new snackbar. The line-spacing looks a little bit tight. And the top and bottom padding around the text looks a bit large. But if its inheriting the same values as the other ones we can leave it for now.

2022-05-11 15:35 UTC, ashiagr approved these changes
Good job @AjeshRPai! Changes look good to me. I just left one nitpick. 

Also, a reminder that [quick start dynamic cards show a category completion message](https://github.com/wordpress-mobile/WordPress-Android/blob/b8fe0e2c7bce524c79c99aa994bfb8318f646d59/WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt#L225-L231) which might coincide with this all tasks completion message. I couldn't test it as I couldn't find skip task optiion for dynamic card -> Plans tasks. Since it is behind a feature flag, let's not worry about it, but we can create an issue with existing GH label `My Site Dynamic Cards` to track it.

2022-05-11 15:35 UTC, ashiagr commented on WordPress/src/main/res/values/strings.xml
> +
Nitpick: There are double line spaces, one empty line can be removed.

2022-05-11 18:20 UTC, AjeshRPai commented
@osullivanchris 

>The line-spacing looks a little bit tight. And the top and bottom padding around the text looks a bit large. But if its inheriting the same values as the other ones we can leave it for now.

I have used the same component and haven't done any changes related to the UI behaviour of that component(snackbar), It's the same.

2022-05-11 18:21 UTC, AjeshRPai commented on WordPress/src/main/res/values/strings.xml
> +
@ashiagr  👍🏼  Removed in [6a4fc13](https://github.com/wordpress-mobile/WordPress-Android/pull/16505/commits/6a4fc1351f90766dcdf2d48d32b43c73378f08e8)

2022-05-11 18:36 UTC, merged