QR Code Auth: Part 6 - Save/Restore state and render UI
wordpress-mobile/WordPress-Android pull request #16711
Opened 2022-06-04 01:54 UTC by zwarm

Parent #16481 

This PR adds the following for the QRCodeAuth flow
- Saving and restoring from savedInstanceState
- Hook in error state handlers
- Render UI for content and error

Notes: 
- This PR will be merged to a feature branch and not trunk. Milestone will be set to "future"

**Merge Instructions**
- Ensure that #16710 has been merged to the feature branch
- Merge as normal

Validated View | Done View
-- | --
<img width="250" height="500" alt="Alt desc" src="https://user-images.githubusercontent.com/506707/171972045-0b6c625f-0cc2-4f3e-9b7e-c3e9490632a9.png"> | <img width="250" height="500" alt="Alt desc" src="https://user-images.githubusercontent.com/506707/171972048-6feb8e0a-032e-4aa1-a377-4e7fdb67ff46.png">

**To test:**
Tests A-B-C are one sequential path
Test A: Validate View - Cancel button
- Install the app
- Login using a WP.com account
- Navigate to Me -> App Settings -> Debug Settings
- Enable `QRCodeAuthFlowFeatureConfig`
- Restart the App
- Navigate back to Me
- Tap the "Scan Login Code" row to launch the scanner
- Scan the attached mock qr code
- ✅ Verify the "Validated" content view is shown
- Tap the "cancel" button
-  ✅ Verify you are returned to the Me view

Test B: Validate View - Log me in button
- Navigate back to Me
- Tap the "Scan Login Code" row to launch the scanner again
- Scan the attached mock qr code
- ✅ Verify the "Validated" content view is shown
- Tap the "Yes, Log me in" button
- ✅ Verify you see the progress overlay on the view 
- ✅ Verify you see the "done" view

Test C: Done view - Dismiss button
- Tap the dismiss button
-  ✅ Verify you are returned to the Me view

Test D: Kill process + restoring state
- Follow test A, but do not tap the "cancel" button
- Background the app
- From the logcat window, tap the "Stop" button to kill the process
- Relaunch the app and you should be taken back to the Validated view
- Tap the "Yes, Log me in" button
- Background the app
- From the logcat window, tap the "Stop" button to kill the process
- Relaunch the app and you should be taken back to the Done view

![WP QRCode](https://user-images.githubusercontent.com/506707/171970351-7ac1ec69-a2c2-4ed7-b646-b7803c806930.png)

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
The viewmodel test is coming in a future PR

PR submission checklist:

- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-06-07 07:58 UTC, AjeshRPai requested changes
I have looked at the code changes and tested them per the instructions.
Test A, B and C looks good to me 👍🏼 🟢 

While testing the scenario D, I encountered a crash at one point , Please find below the details of the crash. I couldn't reproduce this issue. While I was trying to video capture this issue. I found that the state is not restored as expected. 🤔 . Could you take a look at these issues and let me know if I have followed steps correctly or if you need any additional info.

Tested on Samsung s10,Android 12 

Issue 1 - Crash on Test D
<details>
<summary>Crash log </summary>
```Process: org.wordpress.android.prealpha, PID: 17737
    java.util.MissingFormatArgumentException: Format specifier '%2$s'
        at java.util.Formatter.format(Formatter.java:2529)
        at java.util.Formatter.format(Formatter.java:2459)
        at java.lang.String.format(String.java:2911)
        at android.content.res.Resources.getString(Resources.java:627)
        at android.content.Context.getString(Context.java:726)
        at org.wordpress.android.ui.utils.UiHelpers.getTextOfUiString(UiHelpers.kt:35)
        at org.wordpress.android.ui.utils.UiHelpers.setTextOrHide(UiHelpers.kt:56)
        at org.wordpress.android.ui.qrcodeauth.QRCodeAuthFragment.applyContentState(QRCodeAuthFragment.kt:80)
        at org.wordpress.android.ui.qrcodeauth.QRCodeAuthFragment.renderUi(QRCodeAuthFragment.kt:69)
        at org.wordpress.android.ui.qrcodeauth.QRCodeAuthFragment.access$renderUi(QRCodeAuthFragment.kt:29)
        at org.wordpress.android.ui.qrcodeauth.QRCodeAuthFragment$observeViewModel$3.invokeSuspend(QRCodeAuthFragment.kt:49)
        at org.wordpress.android.ui.qrcodeauth.QRCodeAuthFragment$observeViewModel$3.invoke(Unknown Source:8)
        at org.wordpress.android.ui.qrcodeauth.QRCodeAuthFragment$observeViewModel$3.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:136)
        at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:398)
        at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:375)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at org.wordpress.android.ui.qrcodeauth.QRCodeAuthViewModel.postUiState(QRCodeAuthViewModel.kt:191)
        at org.wordpress.android.ui.qrcodeauth.QRCodeAuthViewModel.startOrRestoreUiState(QRCodeAuthViewModel.kt:76)
        at org.wordpress.android.ui.qrcodeauth.QRCodeAuthViewModel.start(QRCodeAuthViewModel.kt:60)
        at org.wordpress.android.ui.qrcodeauth.QRCodeAuthFragment.startViewModel(QRCodeAuthFragment.kt:53)
        at org.wordpress.android.ui.qrcodeauth.QRCodeAuthFragment.onViewCreated(QRCodeAuthFragment.kt:42)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
        at android.app.Activity.performStart(Activity.java:8315)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)```

</details>

Issue 2 - State is not restored

https://user-images.githubusercontent.com/17463767/172327517-5ba16329-a461-4286-833c-63db812ffb39.mp4

2022-06-13 16:22 UTC, zwarm commented
@AjeshRPai  🙇  Thanks for all the testing and feedback. :)

> ### Issue 1 - Crash on Test D
I found this issue later on and corrected it in PR #16713 in the `Authenticating` data class. I didn't come back and update this PR. So I'm noting the fix here, but won't update this PR.

> ### Issue 2 - State is not restored
Thank you for the video. How did you kill the process? I tried a bunch of scenario's and found that the app restore works differently depending on where/when/how the app is killed (outside of being in the scan view). Sometimes it goes back to the Me view. It's weird. Let's have a quick chat about this, it may be easier. Thanks

2022-06-13 17:54 UTC, zwarm commented
@AjeshRPai - I created a new bug #16738 for the state part. I will address it once the feature branch is all together. Would you be so kind as to approve this PR. I've cc'd you on the new issue. Thanks

2022-06-14 00:31 UTC, AjeshRPai approved these changes
> Would you be so kind as to approve this PR. I've cc'd you on the new issue. Thanks

@zwarm Sure 👍🏼 

>Thank you for the video. How did you kill the process? I tried a bunch of scenario's and found that the app restore works differently depending on where/when/how the app is killed (outside of being in the scan view). Sometimes it goes back to the Me view. It's weird. Let's have a quick chat about this, it may be easier. Thanks

👍🏼

2022-06-14 00:34 UTC, merged