Migration: Android 12 Unsafe Intent launches
wordpress-mobile/WordPress-Android pull request #16739
Opened 2022-06-14 07:24 UTC by AjeshRPai

Fixes #

To test:
In order to test this change the add the following code to the app start up and run the app in an Android 12 device. 
```
StrictMode.setVmPolicy(
                VmPolicy.Builder()
                // Other StrictMode checks that you've previously added.
                // ...
                .detectUnsafeIntentLaunch()
                .penaltyLog()
                .penaltyDeath()
                // Consider also adding penaltyDeath()
                .build())
```

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-06-14 13:28 UTC, ashiagr requested changes
👋 @AjeshRPai, thank you for giving it a try but looks like we need to be a bit careful here. I left a note with a potential issue in the solution. 

Hope it makes sense. We can discuss it if you need any help.

2022-06-14 13:28 UTC, ashiagr commented on WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
> +        Intent i = new Intent();
By replacing `getIntent()` to `new Intent()` we'll be losing already existing intent extra data (e.g. `SITE`, `postModelLocalId`):

<img width="700" alt="intent extra" src="https://user-images.githubusercontent.com/1405144/173585456-d96b41cf-6655-45a6-962a-03d895785449.png">

which might be [needed by the calling activity's `onActivityResult()` ](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L1141-L1154).

Some of the [suggestions](https://developer.android.com/guide/components/intents-filters#UseIntentsMoreResponsibly) we can try:

- Copy only the essential extras within intents, and perform any necessary sanitation and validation.
   To the new `Intent`, you can copy intent extra data that might be needed by the calling activities. 

- Don't export your app's components unnecessarily. 
   Test that `EditPostActivity` is not invoked from any external process and mark `exported=false` in `AndroidManifest`.

2022-07-01 21:06 UTC, RenanLukas commented
Hey @AjeshRPai and @ashiagr  👋 
I've submitted a PR with a possible fix for this issue: #16851

2022-07-04 11:27 UTC, ashiagr commented
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/pull/16851.

2022-07-04 11:27 UTC, closed without merging