No Network check in site settings
wordpress-mobile/WordPress-Android pull request #16737
Opened 2022-06-13 13:10 UTC by carl-duncan

Fixes #

Added the network check to onResume

To test:

Go into site settings
Open the tags
Go into airplane mode
Go into the app and close the tags section

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-06-15 07:20 UTC, AjeshRPai requested changes
@carl-duncan Thanks for working on this Issue.

I can see the same issue when I follow the below steps 
- Go to My Site -> Site Settings 
- Enable Airplane Mode
- Go to Tags
- Click at create Tag and Enter tag details 
- Notice that on pressing add tag the screen freezes 

https://user-images.githubusercontent.com/17463767/173766976-1da7d77e-1899-4cc7-8c8b-2053d62cbed9.mp4

Let me know if you need any additional info

2022-06-15 18:41 UTC, carl-duncan commented
Thank you I will check it out!

2022-06-15 19:27 UTC, carl-duncan commented
@AjeshRPai  Hey , fixed the issue for that specific interaction

2022-06-17 11:06 UTC, AjeshRPai commented
@carl-duncan Thanks for making the change. I feel now the behaviour is not user-friendly. When the user clicks on a setting, I would say it's better to show a snack bar with no connection message rather than closing the site settings page itself. The user might be unable to figure out what went wrong there as there are items like Site Title, Tag line etc., which we can edit without the internet. WDYT?

2022-06-17 13:44 UTC, carl-duncan commented
> @carl-duncan Thanks for making the change. I feel now the behaviour is not user-friendly. When the user clicks on a setting, I would say it's better to show a snack bar with no connection message rather than closing the site settings page itself. The user might be unable to figure out what went wrong there as there are items like Site Title, Tag line etc., which we can edit without the internet. WDYT?

Yeah I agree, It would be a better user experience and easier for them to take their next step to fix the connection and continue.

2022-06-17 15:24 UTC, carl-duncan commented
Hey @AjeshRPai , I added a toast to display when a user is trying to save a toast when there is no connection. I think that would be the best course of action as users will still have easy access to create a tag once they get connectivity and not break the UI.

2022-06-20 14:05 UTC, AjeshRPai commented
@carl-duncan I have tested the latest changes. I still see the freezing issue when I try to add a tag without internet. Please find the below video capture showing the behaviour. 

https://user-images.githubusercontent.com/17463767/174618822-b01c161f-40d4-4a4d-8dbd-7d69eadd6c43.mp4

I believe the better fix would be to show a no internet toast on clicking at the Tags/Timezone settings if we don't have internet. No need to finish the activity but show the No Internet connection toast. WDYT?. 🤔

2022-06-20 15:06 UTC, carl-duncan commented
> @carl-duncan I have tested the latest changes. I still see the freezing issue when I try to add a tag without internet. I am not able to see any toast with an internet connection error. Please find the below video capture showing the behaviour.
> 
>  Screen_Recording_20220620-192050_WordPress.Pre-Alpha.mp4 
> I believe the better fix would be to show a no internet toast on clicking at the Tags/Timezone settings if we don't have internet. No need to finish the activity but show the No Internet connection toast. WDYT?. 🤔

Hey @AjeshRPai could you retest with mobile data off as well?

2022-08-11 08:06 UTC, AjeshRPai commented
Hey @carl-duncan , Sorry for the late reply. 

>Hey @AjeshRPai could you retest with mobile data off as well

Same behaviour as above in the Video capture. The screen freezes.

2022-09-07 08:56 UTC, AjeshRPai requested changes
.

2023-12-01 00:35 UTC, closed without merging