Stats revamp v2:  Remove feature config
wordpress-mobile/WordPress-Android pull request #16989
Opened 2022-08-03 03:46 UTC by ravishanker

This PR remove **StatsRevampV2 Feature Config**, **Stats New Feature Intro**  and updates all the places that was in use including analytics and prefs.

Fixes #16988 

To test:

- Build and run
- Launch **Jetpack app**
- Go to App Settings (Tap on Avatar at the top right hand corner on My Site -> Find App Settings)
- Select Debug Settings
- Ensure **StatsRevampV2FeatureConfig** is not present
- Ensure no Stats Feature Intro is shown
- Navigate to Stats, and ensure the new cards are shown or a pop-up is displayed about update and new cards shown
- Also, launch **WordPress app** and ensure it is still showing old stats cards on Stats screen.

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
updated unit tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-08-03 18:37 UTC, irfano requested changes
My manual test was successful, but some unit tests fail after removing the flag.

2022-08-03 18:37 UTC, irfano commented on WordPress/build.gradle
> +        buildConfigField "boolean", "MY_SITE_DEFAULT_TAB_EXPERIMENT_VARIANT_DASHBOARD", "false"
`MY_SITE_DEFAULT_TAB_EXPERIMENT` and `MY_SITE_DEFAULT_TAB_EXPERIMENT_VARIANT_DASHBOARD` don't look related to this PR. Did they come from trunk merge?

2022-08-03 18:37 UTC, irfano commented on WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
> +//        statsRevampV2FeatureConfig: StatsRevampV2FeatureConfig,
np: I'd prefer removing this instead commenting.

2022-08-03 23:24 UTC, ravishanker commented on WordPress/build.gradle
> +        buildConfigField "boolean", "MY_SITE_DEFAULT_TAB_EXPERIMENT_VARIANT_DASHBOARD", "false"
Yes

2022-08-03 23:33 UTC, ravishanker commented on WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
> +//        statsRevampV2FeatureConfig: StatsRevampV2FeatureConfig,
Thanks for spotting it.  Cleaned-up now.

2022-08-03 23:35 UTC, ravishanker commented
> My manual test was successful, but some unit tests fail after removing the flag.

I did update unit tests.  They ran successfully locally and also the build as you can see is also green.  What unit tests are failing for you and why?

2022-08-04 11:04 UTC, irfano commented
> I did update unit tests. They ran successfully locally and also the build as you can see is also green. What unit tests are failing for you and why?

`InsightsManagementMapperTest` was the failing test. But they are working now. Maybe it was a cache problem on my local.

2022-08-04 11:09 UTC, irfano approved these changes
Removing feature config change LGTM! 👍🏻 
I'm approving, but I'm not sure about added `MY_SITE_DEFAULT_TAB_EXPERIMENT` and `MY_SITE_DEFAULT_TAB_EXPERIMENT_VARIANT_DASHBOARD`. They came from the trunk merge, but they should have not been in the diff of the PR. The current trunk doesn't contain `MY_SITE_DEFAULT_TAB_EXPERIMENT`.
I think we should remove them from this PR. WDYT?

2022-08-05 00:09 UTC, ravishanker commented
> Removing feature config change LGTM! 👍🏻 I'm approving, but I'm not sure about added `MY_SITE_DEFAULT_TAB_EXPERIMENT` and `MY_SITE_DEFAULT_TAB_EXPERIMENT_VARIANT_DASHBOARD`. They came from the trunk merge, but they should have not been in the diff of the PR. The current trunk doesn't contain `MY_SITE_DEFAULT_TAB_EXPERIMENT`. I think we should remove them from this PR. WDYT?

Both those lines have been removed

2022-08-05 00:59 UTC, merged