Jetpack Social: Update the strings to reflect the new publicize branding
wordpress-mobile/WordPress-Android pull request #17109
Opened 2022-08-31 19:47 UTC by enejb

Updates the Apps to have make Jetpack Social more predominant in the apps.
See pdrWKz-vt-p2

To test:
TBD.

## Regression Notes
1. Potential unintended areas of impact
No regressions this is just a text change.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Looked at the UI in the PR. 

3. What automated tests I added (or what prevented me from doing so)
none.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-09-01 10:14 UTC, AjeshRPai approved these changes
@enejb I have tested the changes. All looks fine to me 👍🏼 

I am not sure whether the changes to `fastlane/resources/values/strings.xml` is needed or not. 🤔 . Maybe I am missing something. I will let @zwarm confirm it. 


>Go to Site > Settings > Sharing
Notice the new label.
Add a social account. Notice it says share post to %.

🟢  Works as expected

>Test 2
Go create a new post.
Select Post settings.
Notice it says Jetpack Social as a heading for the social connections.

 I couldn't test this, am not sure whether these are the right steps or am missing something. 🤔 

As such I don't see anything blocking. I am approving but not merging so that @zwarm can have a look.

2022-09-01 13:04 UTC, zwarm commented
@enejb 
Same as @AjeshRPai , I could not follow the steps "Test 2" - I don't see a sharing option.

And @AjeshRPai is also correct, we don't change the fastlane files, just the `strings.xml`. So please revert that commit. 🙏 .

❓ Just to be double check, you want the text to read `Jetpack Social Connections` in both the WordPress app and the Jetpack app, correct? If this is not the case, then you need to add the value to the Jetpack [strings.xml](WordPress/src/jetpack/res/values/strings.xml) instead of the WordPress [strings.xml](WordPress/src/main/res/values/strings.xml) file. Adding it to the WordPress file will change it for both apps.

2022-09-01 13:49 UTC, zwarm requested changes
Please revert the fastlane commit. It is not necc. to directly change those file. Thanks.

2022-09-01 18:23 UTC, enejb commented
@zwarm and @AjeshRPai I reverted the changes to fast lane and got more feedback Kristina Plauché. The chance should be the same on Jetpack and WP apps. I also updated wording from `Share your post %` to just `Share post %`. This way it lines up with iOS as well. 

I think this is ready to merge now. But please take another look in case I missed something

2022-09-02 10:55 UTC, AjeshRPai approved these changes
Everything LGTM 👍🏼 . @zwarm Since you had requested changes, GitHub is not showing me the option to merge the PR. Once you have a look at it, please feel free to merge.

2022-09-02 16:19 UTC, zwarm approved these changes
Nice work @enejb . Thanks for reverting the fastlane file. :shipit:

2022-09-02 16:19 UTC, merged