Stats Revamp: match data across platforms
wordpress-mobile/WordPress-Android pull request #17745
Opened 2023-01-12 04:53 UTC by ravishanker

This PR fixes data consistencies across Web, Android and iOS on Jetpack app

- Comparison between this week and last week excludes today's data
- Labels now read **7-days** instead of **Week**

Fixes #17731 

<img width=320 src="https://user-images.githubusercontent.com/990349/211978398-2b84d8e5-ca38-431e-abdc-64bf53b4282a.png" />

To test:

- Launch Jetpack app
- Navigate to Stats
- Verify the titles on the Views and Visitors card read as **Last 7-days** and **Previous 7-days**
- Verify Information below the graph uses the same like **7-days**
- Verify information on the Total Likes also reads like **7-days**
- Verify information on the Total Comments also reads **7-days** and not Week
- Also verify the Total count of Views, Visitors, Likes and Comments matches on the Web

>**Note**
> The Line graph on Views and Visitors card still shows data for today and matches Web
> There's a know issue around Unique Visitors, that's not related to this fix

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-01-12 14:00 UTC, staskus commented
Hey, thanks for the changes. I'll soon make an equivalent on iOS. However, I am concerned about the graph.

> The Line graph on Views and Visitors card still shows data for today..

I do think that's misleading for users. If we're labeling the data as "Last 7-days" we should be explicit in the representation of which days we're talking about. 

> ..and matches Web

There's no graph for the 7-day highlights elements, which part does it match? I may be missing some context. Thanks!

<img width="1452" alt="image" src="https://user-images.githubusercontent.com/4062343/212085896-9bbb1189-5b3b-49c6-85ba-121763c23e8f.png">

2023-01-12 14:13 UTC, staskus commented
I found one issue:

By going into "Week >" I can see that the numbers don't match the web. Android also adds the view count for one more day (January 8th), although the graph and date are from January 9th.

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/4062343/212088784-84a94561-c518-4741-b266-d19265e5ac17.png">

2023-01-12 16:52 UTC, irfano commented
>The Line graph on Views and Visitors card still shows data for today and matches Web

Will we fix it too?

2023-01-12 21:55 UTC, irfano requested changes
- We used to fetch 15 days and we don't use 15 days anymore, right? But usecases are still sending 15 days data to the mappers. If they send 14 days, then we wouldn't need `dropLast(1)`.
- I think previous strings were more proper on the detail screens. Blue line shows "This Week (4 days)", not "Last 7-days". Wdyt?
<img src="https://user-images.githubusercontent.com/2471769/212188504-fcbddca2-e6be-41b8-b1e4-c6a1ffab8177.png" width=200>

2023-01-12 21:55 UTC, irfano commented on WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TotalStatsMapper.kt
> +        // taking data for last 14 days excluding today
> // taking data for last 14 days excluding today

Is this comment correct? This function still returns 7 days, not 14.

2023-01-13 03:26 UTC, ravishanker commented
> Hey, thanks for the changes. I'll soon make an equivalent on iOS. However, I am concerned about the graph.
> 
> > The Line graph on Views and Visitors card still shows data for today..
> 
> I do think that's misleading for users. If we're labeling the data as "Last 7-days" we should be explicit in the representation of which days we're talking about.
> 
> > ..and matches Web
> 
> There's no graph for the 7-day highlights elements, which part does it match? I may be missing some context. Thanks!
> 
> <img alt="image" width="1452" src="https://user-images.githubusercontent.com/4062343/212085896-9bbb1189-5b3b-49c6-85ba-121763c23e8f.png">

Referring the bar chart below the highlights section

2023-01-13 03:31 UTC, ravishanker commented
> I found one issue:
> 
> By going into "Week >" I can see that the numbers don't match the web. Android also adds the view count for one more day (January 8th), although the graph and date are from January 9th.
> 

Strange but true.  The detail view is returning a different range of data.  On insights it is returning last 15 days counting from today backwards (30-Dec to 13-Jan) while the Week detail view is returning from 1-Jan to 15-Jan.

Good catch.  Fixed now.  Thanks

2023-01-13 03:41 UTC, ravishanker commented
> * We used to fetch 15 days and we don't use 15 days anymore, right? But usecases are still sending 15 days data to the mappers. If they send 14 days, then we wouldn't need `dropLast(1)`.
>  
When you fetch 14 days it returns 14 days including today, whereas we need 14 days excluding today, so need to fetch 15 and drop last
>     * I think previous strings were more proper on the detail screens. Blue line shows "This Week (4 days)", not "Last 7-days". Wdyt?
> 
Then we need to change Previous 7 days to Last Week too.

2023-01-13 03:44 UTC, ravishanker commented on WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TotalStatsMapper.kt
> +        // taking data for last 14 days excluding today
The comment is not for the function, just in case someone is wondering why last element is being dropped.

2023-01-13 22:52 UTC, irfano approved these changes
>When you fetch 14 days it returns 14 days including today, whereas we need 14 days excluding today, so need to fetch 15 and drop last

Yes, I missed that. We still need 15 days on the detail screen. 👍🏻 

The wrong value on the detail screen is fixed. LGTM!

2023-01-15 14:57 UTC, staskus commented
Thank you for the changes in the graph!

🔴 I compared the numbers on iOS, Android, and the Web and I don't know why Android is reporting a lower number. The calculator represents Web's daily numbers added one by one.

After further investigation, I saw that Android calculates the numbers for one day behind. Jan 7 - Jan 13, when it's supposed to calculate the total for days Jan 8 - Jan 14 (as the graph shows).

CC @ravishanker, @irfano 

<img width="804" alt="Difference V   V Insights" src="https://user-images.githubusercontent.com/4062343/212548269-ec822c67-6ad1-4238-aadb-6fadb7c1da61.png">

2023-01-15 22:28 UTC, merged

2023-01-15 22:36 UTC, ravishanker commented
> Thank you for the changes in the graph!
> 
> 🔴 I compared the numbers on iOS, Android, and the Web. Android is reporting a different number. The calculator represents Web's daily numbers added one by one.
> 
> After further investigation, I saw that Android calculates the numbers for one day behind. Jan 7 - Jan 13, when it's supposed to calculate the total for days Jan 8 - Jan 14 (as the graph shows).
> 
> CC @ravishanker, @irfano

If the 14th is today, then it needs to be excluded to match with Web right?  Then it is correct.
The graph as mentioned before [still show today, just as Bar chart on Web ](https://github.com/wordpress-mobile/WordPress-Android/pull/17745#issuecomment-1381268103)

2023-01-16 06:06 UTC, staskus commented
> > Thank you for the changes in the graph!
> 
> > 
> 
> > 🔴 I compared the numbers on iOS, Android, and the Web. Android is reporting a different number. The calculator represents Web's daily numbers added one by one.
> 
> > 
> 
> > After further investigation, I saw that Android calculates the numbers for one day behind. Jan 7 - Jan 13, when it's supposed to calculate the total for days Jan 8 - Jan 14 (as the graph shows).
> 
> > 
> 
> > CC @ravishanker, @irfano
> 
> 
> 
> If the 14th is today, then it needs to be excluded to match with Web right?  Then it is correct.
> 

@ravishanker, thanks for the reply!

It was Jan 15th, showing the graph until Jan 14th, and loading the data until Jan 13th. I will retest today as well to see what it shows.

> The graph as mentioned before [still show today, just as Bar chart on Web ](https://github.com/wordpress-mobile/WordPress-Android/pull/17745#issuecomment-1381268103)

Bar chart on the web is a separate element. For me, it's misleading showing calculations for a different data range than displayed on the graph. I'm delaying to merge iOS PR so we could have exactly same behavior and synchronize our solutions.

CC: @irfano and @guarani (since you just revied iOS PR)

2023-01-16 13:48 UTC, staskus commented
> After further investigation, I saw that Android calculates the numbers for one day behind. Jan 7 - Jan 13, when it's supposed to calculate the total for days Jan 8 - Jan 14 (as the graph shows).

I can no longer reproduce this issue. I turned back the clock to yesterday but now the graph was until Jan 15th and calculations until Jan 14th. I've no idea why I had that behavior yesterday 🤷‍♂️.

---

The only question for me remains the fact that we continue showing the graph up to today. I think we have a disagreement here so it would be good to hear other opinions.

2023-01-16 14:31 UTC, irfano commented
> I can no longer reproduce this issue. I turned back the clock to yesterday but now the graph was until Jan 15th and calculations until Jan 14th. I've no idea why I had that behavior yesterday 🤷‍♂️.

What was the time when you tested yesterday? Could it be related to timezone difference?

> 
> The only question for me remains the fact that we continue showing the graph up to today. I think we have a disagreement here so it would be good to hear other opinions.

IMO, it's better to remove today from the line chart of "Views & Visitors".

2023-01-16 14:44 UTC, staskus commented
> What was the time when you tested yesterday? Could it be related to timezone difference?

It's visible on the screenshot, so I tried to come back at the exact same time. Maybe something was wrong with the emulator.