Enable VideoPress block on Android
wordpress-mobile/WordPress-Android pull request #17928
Opened 2023-02-08 11:30 UTC by SiobhyB

Fixes #

To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-02-08 15:59 UTC, SiobhyB commented on WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
> +        return site != null && site.isWPCom();
Enabled only on simple WordPress.com sites for now and added [a task to the project board](https://github.com/orgs/wordpress-mobile/projects/166/views/1?layout=board) for this to eventually be changed to match the web.

2023-02-13 11:05 UTC, fluiddot requested changes

2023-02-13 11:05 UTC, fluiddot commented on build.gradle
> +    gutenbergMobileVersion = '5459-0b4b05d499197825893260921c662ed3d45a6f33'
We'd need to update this reference to the latest commit: `364d743d55c79c0eb462a1df79520173bcb8aab9`.

2023-02-13 11:05 UTC, fluiddot commented on build.gradle
> +    gutenbergMobileVersion = '5459-1e82ee9edc7a4fa5058fadfdb8da6735b94cf933'
@SiobhyB This reference is no longer valid as the commits in the GB-mobile PR have been recreated due to a rebase ([reference](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5459#event-8502143957)). The last commit SHA that could be used here is: `81826df1f59b0002c77e7bc6a0dc4356fed2b273`.

2023-02-14 09:35 UTC, fluiddot approved these changes
LGTM 🎊 !

I checked that the VideoPress block is displayed as unsupported and that can be edited via UBE (Unsupported Block Editor) on Atomic sites.

**NOTE:** On Simple sites when using UBE, it shows a warning due to the block not being available on the site. This is expected as the block on web hasn't being released yet to users.

_Tested build `pr17928-0ce5520` on a Samsung Galaxy S20 FE 5G (Android 13)._

2023-02-15 11:20 UTC, merged