[Domain Purchasing during Site Creation] Add tracks events
wordpress-mobile/WordPress-Android pull request #17967
Opened 2023-02-16 15:55 UTC by antonis

Fixes #17915

To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-02-24 17:08 UTC, ovitrif commented on WordPress/src/main/java/org/wordpress/android/ui/domains/DomainsRegistrationTracker.kt
> +class DomainsRegistrationTracker @Inject constructor(val tracker: AnalyticsTrackerWrapper) {
Thank you for extracting the domains tracking to this dedicated `tracker` 🙇🏻

2023-02-24 17:14 UTC, ovitrif requested changes
Great work! Progress LGTM up to this point @antonis 🙇🏻 

I didn't see anything logic that depends on the feature flag in the changes though 🤷🏻 , which explains why during testing the new event properties are tracked regardless of the feature flag state (ON/OFF).

## Testing:
- ### 🌕 Domains Selected - domain_cost property
  - #### 🟢 Feature flag ON
    ```
    17:56:40.531 WordPress-STATS      com.jetpack.android.beta   I  🔵 Tracked: enhanced_site_creation_domains_selected, Properties: {"chosen_domain":"testedbyovitracksdomains001.news.blog","search_term":"testedbyovitracksdomains001","domain_cost":"free"}
    ```
  - #### 🔴 Feature flag OFF
    The event was still fired with the `domain_cost` property for me:

    ```
    17:57:34.882 WordPress-STATS      com.jetpack.android.beta   I  🔵 Tracked: enhanced_site_creation_domains_selected, Properties: {"chosen_domain":"testedbyoviwopurchasingfeaturetracks002.wordpress.com","search_term":"testedbyoviwopurchasingfeaturetracks002","domain_cost":"free"}
    ```

  The experiment event was not fired though, it's only once in my logs:
    ```
    17:55:38.759 WordPress-STATS      com.jetpack.android.beta   I  🔵 Tracked: enhanced_site_creation_domain_purchasing_experiment, Properties: {"variation":"control"}
    ````


- ### 🌕 Webview Viewed - origin property
  - #### 🟢 Feature flag ON
    ```
    17:59:46.436 WordPress-STATS      com.jetpack.android.beta   I  🔵 Tracked: domains_purchase_webview_viewed, Properties: {"origin":"menu","blog_id":215977563,"is_jetpack":false,"site_type":"blog"}
    ```

  - #### 🔴 Feature flag OFF
    The event still had the `origin` property when the feature flag is off for me:
    ```
    18:03:47.282 WordPress-STATS      com.jetpack.android.beta   I  🔵 Tracked: domains_purchase_webview_viewed, Properties: {"origin":"menu","blog_id":215977563,"is_jetpack":false,"site_type":"blog"}
    ```

## Other

> 5. Site created with paid domain event
> This could tracked in (1) but we should re-examine if a new property is needed in the site_created event

> I did not add the other 2 events mentioned in the issue as I am not sure how to test them also domains_registration_form_submitted seem to already exist in code. I think we need revisit them once the flow is in place.

Sounds good to me @antonis 👍

2023-03-01 14:38 UTC, antonis commented
Thank you for reviewing and your feedback @ovitrif 🙇 

> I didn't see anything logic that depends on the feature flag in the changes though 🤷🏻 , which explains why during testing the new event properties are tracked regardless of the feature flag state (ON/OFF).

Good catch 👍 
I agree that the control variation is not supposed to change anything and implemented the change with 097a4e7bf98e79cf981fe4f218dface2d0d6c057

Ready for another pass 🤞

2023-03-01 15:20 UTC, ovitrif approved these changes
Everything LGMT after the last update @antonis 🙇🏻

Thank you for wrangling this and addressing my feedback 🥇 

I'll merge the PR 👍🏻 , any other events can be added when the functionality is available.

2023-03-01 15:21 UTC, merged