Implements Check for Site eligibility for Blaze in Publised Posts
wordpress-mobile/WordPress-Android pull request #18026
Opened 2023-03-01 11:23 UTC by AjeshRPai

Part of #17911

## What? 
This PR adds the implementation to check whether a site is eligible of blaze in the flow Posts → Published Posts . 

In this PR I have also added  a few checks before we make an API call to fetch the Blaze status 
- Check if the User is eligible with `siteModel.isAdmin` check
- Check if the App is **Jetpack** pack and Flag is enabled

 ## How? 

# Testing instructions

## Test - Blaze is not available

1. Go to the **Jetpack** app
2. 🚪 Login with a wp account without Administrator privileges or Use a private site 
3. ⛳ Go to **app settings** → **Debug settings →** enable feature flag → `blaze`
4. 👉🏻Go to Posts → Published Posts 
5. 👆🏻Click on the more icon ⁞ → 
6. ✅ Verify that the **🔥 Promote with Blaze** is not shown 

## Test - Blaze is available

1. Go to the **Jetpack** app
2. 🚪 Login with a wp account with Administrator privileges 
3. ⛳ Go to **app settings** → **Debug settings →** enable feature flag → `blaze`
4. 👉🏻Go to Posts → Published Posts 
5. 👆🏻Click on the more icon ⁞ → 
6. ✅ Verify that the **🔥 Promote with Blaze** is shown 

## Test - Blaze status is not fetched - Monitor on Logcat

1. Go to the **WordPress** app
2. 🚪 Login with a wp account with Administrator privileges 
3. ✅ Verify that the API is not called 
    - Open the logcat
    - Make sure that there is no occurrence of the event **`BlazeStore: fetch blaze status`**
4. ⛳ Go to **app settings** → **Debug settings →** enable feature flag → `blaze`
5. Go to the Home page 
6. Verify Step 4 again

## Regression Notes
1. Potential unintended areas of impact
- Blaze eligibility for a site is not fetched on Jetpack app and flag enabled 
- Blaze eligibility for a site is not checked on the Posts → Published Posts flow

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual tests and relied on the existing Unit tests

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-03-01 13:28 UTC, AjeshRPai commented
Hey @zwarm 👋🏼 

After testing thoroughly, I found out that the logic for checking whether a site has Blaze eligibility is not triggered before listing the Published posts. Hence no posts had the **Promote with Blaze** option in more menu. On Further investigation, I found out that there is two view models for PostListing. 😅 . So to clarify what I have done here and for my reference, I am explaining it below. Feel free to ignore if you understood with the commits or file changes. 

The current view models and the existing logic(abstracted for the context of this PR)
1. `PostListMainViewModel` - Gets initiated first, an object of `PostListViewModelConnector` is created in it 
2. `PostListViewModel` - `PostListFragment` fetches the connector from the `PostListMainViewModel` and passes to the `PostListViewModel` start method 

At first the logic for checking blaze status was in `PostListViewModel`, which I removed with the commit [be78c43](https://github.com/wordpress-mobile/WordPress-Android/pull/18026/commits/be78c438da60210036af7020b13e622833667786) and moved the logic to `PostListMainViewModel` with the [2cd5b96](https://github.com/wordpress-mobile/WordPress-Android/pull/18026/commits/2cd5b9608ef64b968c88e1d38c9874210f131693). In the same commit, I added a property in the connector for Site Blaze eligibility. [Line](https://github.com/wordpress-mobile/WordPress-Android/pull/18026/commits/2cd5b9608ef64b968c88e1d38c9874210f131693#diff-c2bcdfdcc1950d5c14144fcd2e163875b7759d7513d4755ac46eb8c797cf90c8R363).So `PostListMainViewModel` fetches the site eligibility and instantiates the `PostListViewModelConnector` variable with it and then `PostListFragment` fetches the connector from the `PostListMainViewModel` and passes to the `PostListViewModel` start method. 

I hope this helps clarify things.

2023-03-01 16:40 UTC, zwarm commented
@AjeshRPai 
>  On Further investigation, I found out that there is two view models for PostListing. 😅 . So to clarify what I have done here and for my reference, I am explaining it below. 

I really appreciated this explanation; as I haven't delved deep into the posts list logic. 🙇

2023-03-01 18:43 UTC, zwarm requested changes
@AjeshRPai - The "if" wrap in the `PromoteWithBlazeCardSource.build` method is stopping the refresh indicator from disappearing on PTR when blaze is not enabled. I believe the refresh indicator is being checked for each source, but this source never sets/resets it so it gets stuck. Can you take a look? Thanks.

2023-03-02 09:36 UTC, AjeshRPai commented
Hey @zwarm 👋🏼 

I have fixed the infinite loading of the indicator with the commit [ed4ced4](https://github.com/wordpress-mobile/WordPress-Android/pull/18026/commits/ed4ced4eb28f7a38756eb1827bd27b013eb5616d). 

Also, while testing the infinite loading, I found a small issue with the current implementation of the Promote blaze card.

**Issue** - Once we post the `BlazeStatusModel` to the live data on the `fun build`, we are not updating it again on `refresh` → `fetchBlazeStatusAndPostErrorIfAvailable` → `model != null`. We post the same value even if we get a successful response(with or without a blaze status change) from the backend. 

To reproduce this issue, you can 
1. Login with a Blaze-eligible site
2. Disable the feature flag 
3. Go to Dashboard → Verify that the Promote card is not shown 
4. Enable the feature flag 
5. Notice that the Promote card is not shown 

I have fixed this issue with the commit - [e64af0a](https://github.com/wordpress-mobile/WordPress-Android/pull/18026/commits/e64af0ab4419da5dfd714d5a6445efadaca75baa). Let me know if it makes sense.

2023-03-02 12:47 UTC, zwarm commented
>  I have fixed the infinite loading of the indicator  
👍 

> Also, while testing the infinite loading, I found a small issue with the current implementation of the Promote blaze card.
> **Issue** - Once we post the BlazeStatusModel to the live data on the fun build, we are not updating it again on refresh → fetchBlazeStatusAndPostErrorIfAvailable → model != null. We post the same value even if we get a successful response(with or without a blaze status change) from the backend.

> I have fixed this issue 
👍 

I think this is a larger issue with ALL the "sources" and PTR. If you take a look at all the other sources they work exactly the same; no results are returned upon successful fetch. I believe the intent is that a "get" always follows the "fetch", which will then return the result as taken from the db. I've been having doubts about this logic since late last week. @thomashorta just changed the logic in this source and the blogging source to post the last state. I strongly believe that the time has come to review how this works across the board.  

Thanks.

2023-03-02 14:08 UTC, zwarm approved these changes
@AjeshRPai - Thanks for the changes. The indicator is working as expected again. 👏

2023-03-02 14:10 UTC, merged