Remove large titles
wordpress-mobile/WordPress-Android pull request #18070
Opened 2023-03-09 04:53 UTC by ravishanker

This PR updates the following
- Update the icon Reader from cog to following
- Removes large title on Reader
- Removes large title on Notifications

|Before|Rader|Notifications|
|-|-|-|
|![Screenshot_20230309_155059](https://user-images.githubusercontent.com/990349/223920813-6d28b2c4-8a82-458f-98b9-7b5435df0465.png)|![Screenshot_20230309_151635](https://user-images.githubusercontent.com/990349/223919250-687ba7ce-2a65-4735-99ef-06d860029da0.png) |![Screenshot_20230309_153854](https://user-images.githubusercontent.com/990349/223919285-f044b518-a572-4057-b181-bef664f3b24e.png) |

Fixes #

To test:

- Launch WP/JP app
- Navigate to Reader
- Compare the title is smaller and icon is following and not cog as in images above
- Navigate to Notifications
- Compare that title is now smaller

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
existing unit tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-03-09 11:28 UTC, osullivanchris requested changes
👋  Hey @ravishanker the icon change and text size look good. Can we move the page title back into the navigation bar as well though like below?

Know on iOS there's a 'large title' component, we might have had to do something more custom to achieve the large title here, so I'm not sure how easy/hard it is to undo.

<img width="942" alt="Screenshot 2023-03-09 at 11 28 01" src="https://user-images.githubusercontent.com/50576199/224010062-fc10fd09-0f69-4707-9fb1-d83fd42267b2.png">

2023-03-10 01:25 UTC, ravishanker commented
> 👋 Hey @ravishanker the icon change and text size look good. Can we move the page title back into the navigation bar as well though like below?
> 
> Know on iOS there's a 'large title' component, we might have had to do something more custom to achieve the large title here, so I'm not sure how easy/hard it is to undo.
> 
That was easier to do than just the title 😄

2023-03-10 10:31 UTC, osullivanchris approved these changes
Hey @ravishanker  looks good, just tested on my device. Glad it was easier to do it this way! Just one small issue: previously the navigation elements scrolled away on the Notifications tab, but now they're fixed. Not too bad on portrait, but means nearly all the screen is navigation on landscape.

We could also make the reader navigation elements (nav bar, tabs, filter bar) scroll away rather than stay fixed. But I don't think we had that before.

Approving for now anyway as I think that can be addressed as a follow up, not a blocker.

2023-03-13 00:17 UTC, ravishanker commented
> We could also make the reader navigation elements (nav bar, tabs, filter bar) scroll away rather than stay fixed. 
>  
👋  @osullivanchris - No problemo, done 👍

2023-03-13 03:21 UTC, merged

2023-03-13 12:50 UTC, osullivanchris commented
@ravishanker much better thanks. Think this is a good improvement.

One small detail. The filter bar in Reader>Following is still sticky. I don't feel too strongly about it being there. But it does feel like its affecting that navigation stack scrolling away smoothly.