Fixes: the unit test failures after coroutine version udpate
wordpress-mobile/WordPress-Android pull request #18589
Opened 2023-06-08 11:26 UTC by AjeshRPai

Fixes #

To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] Talkback.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] Large and small screen sizes. (Tablet and smaller phones)
- [x] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

2023-06-09 12:59 UTC, ovitrif requested changes
Thanks for this work and the reason it started: that you felt brave and proved to be right when tackling the Coroutines update work 🙇🏻 !

I found a quickfix for the issue we were having in `DomainSuggestionsViewModelTest` and suggested a change via a patchfile 👍🏻 

Everything else LGTM, but IIRC there were more failing tests at CI time, probably the PR is not fully ready. For that reason (my uncertainty) I didn't approve it just yet 👍🏻

2023-06-09 12:59 UTC, ovitrif commented on WordPress/src/test/java/org/wordpress/android/ui/domains/DomainSuggestionsViewModelTest.kt
> +        whenever(productsStore.fetchProducts(any())).thenReturn(mock())
I figured out while trying to fix the failures that we need to stub this call for every test, so I changed it into an inline `mock {…}` declaration, then removed all `whenever`'s for it, and then all tests in the class succeeded 🎉 !

I captured my changes into this patch file:

[fixtest.patch](https://github.com/wordpress-mobile/WordPress-Android/files/11706443/fixtest.patch)

To apply it, copy the file into the root directory of your local repo clone, then run in terminal:
```sh
git apply fixtest.patch
```
🙏🏻

2023-06-09 13:33 UTC, AjeshRPai commented on WordPress/src/test/java/org/wordpress/android/ui/domains/DomainSuggestionsViewModelTest.kt
> +        whenever(productsStore.fetchProducts(any())).thenReturn(mock())
Hey @ovitrif 

Thanks 🙌🏼 . I have applied the patch and committed it [98e0769](https://github.com/wordpress-mobile/WordPress-Android/pull/18589/commits/98e07694a61baf961d59c63d18edc075215b9960)

Thanks for testing and finding this solution. 

Am not really sure why an inline mock worked to be honest. 🤔

2023-06-09 14:28 UTC, ovitrif commented on WordPress/src/test/java/org/wordpress/android/ui/domains/DomainSuggestionsViewModelTest.kt
> +        whenever(productsStore.fetchProducts(any())).thenReturn(mock())
@AjeshRPai My speculation is that we didn't fully understand the actual point where the code failed. The error message was so fuzzy that it sort of meant even the compiler didn't know 😂.

The gist I got of it is that it wasn't really the red test that failed, but "an exception in the previous test". AFAIK Android Studio runs them in random order, so it wasn't really the test written above of the failed one. I went forward and `@Ignore`'d most of them until the ones left no longer failed.

Then randomly (magic intuition I call it, it's a gift I don't always have), I thought: let's rewrite this mock. It ended up fixing the issue 🥳

2023-06-12 19:51 UTC, zwarm commented
@AjeshRPai I'm with Ovi on this one. I pulled this branch and tried the first failing test (as reported by CI) `MediaPickerViewModelTest` and I can't get it to fail locally. However the `ActivityLogViewModelTest` do fail locally. 😮‍💨

2023-06-13 05:54 UTC, ovitrif commented
> @AjeshRPai I'm with Ovi on this one. I pulled this branch and tried the first failing test (as reported by CI) `MediaPickerViewModelTest` and I can't get it to fail locally. However the `ActivityLogViewModelTest` do fail locally. 😮‍💨

Hey folks 👋🏻 , Fyi I've started on working to fix these tests yesterday, sharing with you in hope we don't duplicate the same efforts 🙏🏻 !

I've managed to find some small fixes that made all tests in `ActivityLogViewModelTest` green, I will continue to the next classes.

Mostly doing this to see if the new coroutines version fixes our mutex crash bug (#18589) 😄

2023-06-14 06:45 UTC, ovitrif approved these changes
Should be ready when CI passes 🤞🏻

2023-06-14 07:08 UTC, merged

2023-06-14 07:12 UTC, AjeshRPai commented
Thanks @ovitrif and @zwarm for helping me with this PR  🙌🏼