Blogging reminders don't show prompt if not allowed for blog
wordpress-mobile/WordPress-Android pull request #18739
Opened 2023-07-05 04:35 UTC by ravishanker

This PR is counter part to [a similar fix on iOS.  ](https://github.com/wordpress-mobile/WordPress-iOS/pull/20970)

Currently, the Blogging Reminders feature is only available in the Jetpack app. After the changes in this PR, it's also not available for self-hosted sites not connected to Jetpack. This PR mainly keeps these users from being able to set a Blogging Reminder once with no way to reconfigure it. See https://github.com/wordpress-mobile/WordPress-iOS/issues/20971.

Additionally also removes the `BloggingReminderFeatureConfig` as it has been release over a year ago.

Fixes #20963

To test:
Please [see for details, and instructions for testing](https://github.com/wordpress-mobile/WordPress-iOS/pull/20970)

## Regression Notes
1. Potential unintended areas of impact
Tested on both WP and JP apps

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing, and unit tests

3. What automated tests I added (or what prevented me from doing so)
Updated unit tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-07-05 15:36 UTC, irfano commented on WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsDialogPreference.java
> +            boolean isBloggingRemindersEnabled = mBloggingRemindersProvider != null;
We removed the`mBloggingRemindersProvider.isEnabled()` here, but should we ad other conditions, `buildConfigWrapper.isJetpackApp && site.hasCapabilityEditPosts`

2023-07-06 01:02 UTC, ravishanker commented on WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsDialogPreference.java
> +            boolean isBloggingRemindersEnabled = mBloggingRemindersProvider != null;
Notifications are removed on WP.  There's no need to check again here if it is JP I guess.

2023-07-06 13:24 UTC, irfano commented on WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsDialogPreference.java
> +            boolean isBloggingRemindersEnabled = mBloggingRemindersProvider != null;
Good point!

2023-07-06 13:51 UTC, irfano requested changes
My review is still in progress but I have some comments:
- I think the description is wrong, it mentions `self-hosted sites not connected to Jetpack,` but actually, this PR only removes blogging reminders from WP, nothing related to self-hosted sites. If so, can you update the description properly?
- We checked `hasCapabilityEditPosts`, but it returns false for self-hosted sites even the site has capability. More context: p1688572548724379/1687890995.075909-slack-C0180B5PRJ4
- Reminders button in Site Settings crashes for self-hosted, not Jetpack-connected sites. Actually, the button shouldn't be there. It's a current bug on `trunk` but it doesn't crash on `trunk`. So maybe we can fix that bug here because it causes a new crash here. Wdyt?
 
[device-2023-07-06-164752.webm](https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/b1a86b19-8060-4a4c-9443-cf43aaa28062)

2023-07-07 05:39 UTC, ravishanker commented
> * I think the description is wrong, it mentions `self-hosted sites not connected to Jetpack,` but actually, this PR only removes blogging reminders from WP, nothing related to self-hosted sites. If so, can you update the description properly?

Good point.  Fixed the logic now to cater for self-hosted, non jetpack connected sites

> * We checked `hasCapabilityEditPosts`, but it returns false for self-hosted sites even the site has capability. More context: p1688572548724379/1687890995.075909-slack-C0180B5PRJ4

Removed `hasCapabilityEditPosts` condition check

> * Reminders button in Site Settings crashes for self-hosted, not Jetpack-connected sites. Actually, the button shouldn't be there. It's a current bug on `trunk` but it doesn't crash on `trunk`. So maybe we can fix that bug here because it causes a new crash here. Wdyt?

True, it shouldn't be there at all, removed.

2023-07-07 11:51 UTC, irfano requested changes
Thanks for the changes Ravi!

Why did you add `site.isUsingWpComRestApi` condition? The reminders should be enabled for self-hosted sites too. 
You can check this internal discussion: p1688572319801989/1687890995.075909-slack-C0180B5PRJ4
And also check the updated [iOS PR](https://github.com/wordpress-mobile/WordPress-iOS/issues/20971) description that you mentioned. 

Also, the tests are failing. We ran them multiple times in this PR, I guess they are not flaky.

2023-07-07 13:58 UTC, twstokes commented
👋 @ravishanker! I just wanted to add (which hopefully adds clarity to things) that on iOS the [recent changes](https://github.com/wordpress-mobile/WordPress-iOS/pull/20970) just ensure that `isUserCapableOf(.EditPosts)` is now called when determining if we should show the Blogging Reminders prompt. It just so happens to be for technical reasons that self-hosted sites not connected to Jetpack will return `false` here, making the feature unavailable for those blogs.

I can't identify a business case where we don't want to support self-hosted sites not connected to Jetpack, it's just the client-side logic doesn't allow us to at the moment.

2023-07-08 10:12 UTC, irfano commented
> 👋 @ravishanker! I just wanted to add (which hopefully adds clarity to things) that on iOS the [recent changes](https://github.com/wordpress-mobile/WordPress-iOS/pull/20970) just ensure that `isUserCapableOf(.EditPosts)` is now called when determining if we should show the Blogging Reminders prompt. It just so happens to be for technical reasons that self-hosted sites not connected to Jetpack will return `false` here, making the feature unavailable for those blogs.
> 
> I can't identify a business case where we don't want to support self-hosted sites not connected to Jetpack, it's just the client-side logic doesn't allow us to at the moment.

@twstokes, let me restate what you said to ensure I understand correctly. We're disabling blogging reminders for self-hosted sites that are not connected to Jetpack because we are unable to technically check `isUserCapableOf(.EditPosts)`. Is that correct?

I have found another site property called **`isSelfHostedAdmin`**. We can utilize this condition and we can at least make blogging reminders enabled for self-hosted not Jetpack-connected users who are admin.

2023-07-10 00:30 UTC, ravishanker commented
@irfano - Thanks for the clarification.  Updated PR description to confine it to Feature config removal, and to Jetpack app only. 🙇

2023-07-10 07:04 UTC, pachlava commented
Hey @ravishanker 👋 

I see you've removed an assertion from `e2ePublishSimplePost`. I can see that it failed for WordPress only (where the reminder is removed).

My guess is that because the test still expected for the reminder to be shown (and waited for it for some time), the `Post Published` toast was shown and gone while the test was still waiting for the blogging reminders, resulting in the fail in `verifyPostPublished`. 

I _think_ executing [this line](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/BlockEditorPage.kt#L112) for JP only should resolve the issue.

2023-07-10 12:34 UTC, twstokes commented
> @twstokes, let me restate what you said to ensure I understand correctly. We're disabling blogging reminders for self-hosted sites that are not connected to Jetpack because we are unable to technically check `isUserCapableOf(.EditPosts)`. Is that correct?
> 
> I have found another site property called **`isSelfHostedAdmin`**. We can utilize this condition and we can at least make blogging reminders enabled for self-hosted not Jetpack-connected users who are admin.

Exactly @irfano - that's what way I understand it. Thanks!

2023-07-10 21:35 UTC, irfano requested changes
@ravishanker, can we make blogging reminders enabled for self-hosted admins, as I stated in this [comment](https://github.com/wordpress-mobile/WordPress-Android/pull/18739#issuecomment-1627053537). We can utilize the `isSelfHostedAdmin` parameter for this purpose.

I raised this concern because currently, a user with the "Subscriber" role on a self-hosted, non-Jetpack connected site can set a blogging reminder. However, they are unable to actually publish any posts.

2023-07-10 21:35 UTC, irfano commented on WordPress/src/main/java/org/wordpress/android/ui/mysite/items/listitem/SiteListItemBuilder.kt
> -            !siteUtilsWrapper.isAccessedViaWPComRest(site)
We deleted the` !siteUtilsWrapper.isAccessedViaWPComRest(site)` condition from `buildMeItemIfAvailable`. What does this PR make related to the me button?

2023-07-10 21:35 UTC, irfano commented on WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
>      }
After this change, `removeGeneralSettingsExceptBloggingReminders()` removes everything. I think it would be better to rename the function.

2023-07-11 03:16 UTC, ravishanker commented
Looks like there are a few things mixed up here, and turned out to be something else.  Closing this for now, in favour or not introducing new issues.  Probably, need to raise separate PRs for removing feature config, limiting to JP, and handling self hosted sites

2023-07-11 03:16 UTC, closed without merging