Domain dashboard card: Remove feature flag
wordpress-mobile/WordPress-Android pull request #19135
Opened 2023-09-05 03:18 UTC by ravishanker

Fixes #18725 

Removing domain dashboard card, and clean up all related as it is superseded by Plans project.

To test:

- Launch JP app
- `Go` to Me -> Debug settings
- `Verify` no dashboard_card_domain feature flag is present
- `Go` to Home
- `Verify` **Home**, **Menu** options on dashboard all work as before

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
Existing unit tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-09-05 03:29 UTC, ravishanker commented
@AjeshRPai - FYI

2023-09-05 15:27 UTC, irfano requested changes
We can also remove
- `AppPrefsWrapper.getShouldHideDashboardDomainCard()` and `AppPrefsWrapper.setShouldHideDashboardDomainCard()`.
- "dashboard_card_domain" in feature-flags.json.
- `Partial State.CustomDomainsAvailable`

2023-09-05 15:27 UTC, irfano commented on WordPress/src/androidTest/java/org/wordpress/android/e2e/DashboardTests.kt
> -    }
After removing this, `DomainsScreen` became unused, we can remove it too.

2023-09-05 15:27 UTC, irfano commented on WordPress/build.gradle
> +        buildConfigField "boolean", "DASHBOARD_CARD_ACTIVITY_LOG", "false"
Why did we add `DASHBOARD_CARD_PAGES` and `DASHBOARD_CARD_ACTIVITY_LOG`?

2023-09-05 15:27 UTC, irfano commented on WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
> -                ) : DashboardCard(dashboardCardType = DashboardCardType.DASHBOARD_DOMAIN_CARD)
We can also remove `DashboardCardType.DASHBOARD_DOMAIN_CARD`, right?

2023-09-05 23:46 UTC, ravishanker commented on WordPress/build.gradle
> +        buildConfigField "boolean", "DASHBOARD_CARD_ACTIVITY_LOG", "false"
Probably, came in through trunk merge.  Removed, thanks

2023-09-07 17:43 UTC, irfano approved these changes
Thank you for addressing my comments. I've added one last suggestion and approved the PR. Then you can merge it. LGTM 👍🏻

2023-09-07 17:43 UTC, irfano commented on WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
> -        return DeletablePrefKey.SHOULD_HIDE_DASHBOARD_DOMAIN_CARD.name() + siteId;
We can also remove `DeletablePrefKey. SHOULD_HIDE_DASHBOARD_DOMAIN_CARD`.

2023-09-07 23:23 UTC, merged