UI Modernization Posts: Update post list layout
wordpress-mobile/WordPress-Android pull request #19425
Opened 2023-10-22 20:49 UTC by zwarm

Fixes #19341 

This PR is the second in a series dedicated to updating the post list layout. This PR focuses on updating to the new design for the list. (The context menu will be handled in a separate PR)

To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

2023-10-24 10:41 UTC, osullivanchris requested changes
Great start! There's a lot to love. Looks fresh overall. There's a lot going on here, so I'll also have a few notes as you probably expect.

- The padding at the top and bottom of the cells looks larger than expected in real build. If we defined as 12, can we try 8 instead?
- The skeleton/shimmer state has no left padding which makes it look a little bit broken.
- I am seeing situations where there is 2 lines of heading and 3 lines of excerpt and the cell is getting quite long. We can discuss how we resolved this on iOS per a recent discussion on Slack. But ideal state is for the height of the text to be capped similar to the height of the image.
- What is the horizontal padding between the text and the image? Can we increase slightly?

Thank you for capturing all the different states so thoroughly. Very helpful. a couple details looking at those:
- In search can the state (published, draft, etc) come earlier in that string? Before the author at least?
- In example set two, row 1 we see the example with spaces or different blocks. Is there anything we can do there, like truncate after the viable text or similar, rather than showing a gap and ... ?

2023-10-24 10:52 UTC, AjeshRPai commented on WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
> +            _viewState.value = _viewState.value?.copy(isFabVisible = false, isAuthorFilterVisible = false)
Nice

2023-10-24 14:24 UTC, zwarm commented
Thanks for the feedback @osullivanchris 


Published | Search
-- | --
<img width="250" height="500" alt="Alt desc" src="https://github.com/wordpress-mobile/WordPress-Android/assets/506707/e35b0213-5a58-420e-841d-c1a1d22c5879"> | <img width="250" height="500" alt="Alt desc" src="https://github.com/wordpress-mobile/WordPress-Android/assets/506707/b82b2b18-c57b-4931-a270-c436c9f980ea">

> * The padding at the top and bottom of the cells looks larger than expected in real build. If we defined as 12, can we try 8 instead?

I dropped it down to 8dp. 

> * The skeleton/shimmer state has no left padding which makes it look a little bit broken.

I set a 16dp margin to the start/end 

> * I am seeing situations where there is 2 lines of heading and 3 lines of excerpt and the cell is getting quite long. We can discuss how we resolved this on iOS per a recent discussion on Slack. But ideal state is for the height of the text to be capped similar to the height of the image.

I thought it was: show title only if it took up 3 or more lines of the space, but both excerpt and title had a max of 3 lines each. So if title had 1 line, and excerpt 3 lines, then take all of it. If I understand correctly now, it sounds like there is a max of 3 lines total?  (I haven't supplied an update for this yet)

> * What is the horizontal padding between the text and the image? Can we increase slightly?

It was set to 4dp, I increased it to 8dp. It may look larger/smaller based on how the words on the line fit within the text space.

> * In search can the state (published, draft, etc) come earlier in that string? Before the author at least?

Current prod position is after the author, but I agree, it would look better earlier in the line. I moved it to before the date so it’s easy to spot. I can definitely move it to before the author too, but wanted to give this a try first. 


> * In example set two, row 1 we see the example with spaces or different blocks. Is there anything we can do there, like truncate after the viable text or similar, rather than showing a gap and ... ?

Yeah, glad you picked up on this on too. In the latest update, I am only showing the text prior to the large space gap. wdyt?

2023-10-24 15:30 UTC, zwarm commented
@osullivanchris - I changed the title/excerpt logic. Title is a max of 3 lines, it will have priority, excerpt will take up the remaining number of lines that title does not take up. Let me know what you think. 👍 

<img width="250" height="500" alt="Alt desc" src="https://github.com/wordpress-mobile/WordPress-Android/assets/506707/95995305-1173-4fd0-9ae3-0acb7855446a">

2023-10-24 16:29 UTC, osullivanchris commented
@zwarm thanks for all those fixes. Will they be reflected if I install the build again?

All sound good. Including moving the status before the date in search, 4-8 padding change, only showing text in excerpt.

Just double checking with the iOS folks what we decided on the heading/excerpt logic before I nod to that.

2023-10-24 17:04 UTC, zwarm commented
> @zwarm thanks for all those fixes. Will they be reflected if I install the build again?

Yes, reinstall the build to get all the changes.

2023-10-24 21:18 UTC, zwarm commented
@osullivanchris - okie dokie, I think we are set with title and excerpt. If both are present, title will take priority at two lines and excerpt will take 1. If title has only 1 line, then excerpt will take the two (if there is enough for two). Total of both is a max of three lines. :)

2023-10-25 09:48 UTC, osullivanchris approved these changes
Everything looking much better now except 2 minor padding details:
1. In each cell (except the top one) the top padding looks to be 16 while the bottom padding is 8. Can we make sure the top is also 8?
2. In the top cell, the spacing is 8 and 8, so it seems to somehow appear differently than the rest. So just to make sure it doens't "lose" its top padding if we reduce all by 8 from 16->8. 

<img width="1188" alt="image" src="https://github.com/wordpress-mobile/WordPress-Android/assets/50576199/e79dc7f0-c557-46c8-928d-4c07f2eb4c8c">

2023-10-25 11:40 UTC, AjeshRPai approved these changes

2023-10-25 11:40 UTC, AjeshRPai commented on WordPress/src/main/res/drawable/ic_more_vertical_24dp.xml
> +        android:pathData="M13,13V11H11V13H13ZM13,19V17H11V19H13ZM11,7H13V5H11V7Z"/>
Hey @zwarm 
Can we re-use the more icon from dashboard or someother place instead of adding a new one? 

File: `ic_more_vert_white_24dp`?

I think the existing usage is by setting the icon and then applying a tint at the usage but may be we can set the color of the more icon to "?attr/colorOnSurface" at all places or use the `ic_more_vert_white_24dp` and set a tint in `post_list_item`

2023-10-25 11:40 UTC, AjeshRPai commented on WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemType.kt
>          val actions: List<PostListItemAction>,
Do we need this actions variable anymore? 🤔 . I think the actions and the tests related to the actions is not needed. Let me know If i misunderstand/you plan to remove them in a future PR

2023-10-25 11:41 UTC, zwarm commented on WordPress/src/main/res/drawable/ic_more_vertical_24dp.xml
> +        android:pathData="M13,13V11H11V13H13ZM13,19V17H11V19H13ZM11,7H13V5H11V7Z"/>
👋 @AjeshRPai - I started in that direction, but then I pulled the svg from the GB icon set and they are different. A future PR will be changing the name of that icon to use the following pattern: "gb_ic_iconname".

2023-10-25 11:44 UTC, zwarm commented on WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemType.kt
>          val actions: List<PostListItemAction>,
@AjeshRPai No, we do not need these anymore. I have it on my task list to address separately. This PR was getting to big. Thanks for the reminder 👍

2023-10-25 11:49 UTC, zwarm commented
@osullivanchris 
> 1. In each cell (except the top one) the top padding looks to be 16 while the bottom padding is 8. Can we make sure the top is also 8?

> 2. In the top cell, the spacing is 8 and 8, so it seems to somehow appear differently than the rest. So just to make sure it doens't "lose" its top padding if we reduce all by 8 from 16->8.

I need to go back and rework the layout, even though I am adding 8dp of spacing it's 16dp. I'm going to merge this PR so the base is set, then I'll address this separately. I'll tag you in the followup PR. 🙇 Thanks!!

2023-10-25 11:50 UTC, merged