Plans on site domain display updated card
wordpress-mobile/WordPress-Android pull request #19818
Opened 2023-12-19 08:34 UTC by ravishanker

Fixes #19807, #19808  

| Before | After |
|--------|--------|
| ![Screenshot_20231219_193130](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/1a127106-0ed5-495e-ba72-22b9e91294e8) | ![Screenshot_20231219_183921](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/1b591a26-284b-48a8-a9dd-498bc442c8e0)| 

-----

## To Test:

Test 1
- Launch JP app
- Select a site with a free plan
- Navigate to Domains (My site -> domains or My site -> More... -> domain)
- Verify a new card is displayed as in second image above
- `Tap` on Upgrade to a plan
- `Verify` it launches flow same as plans card on dashboard
- Return to domains
- `Tap` on Just search for a domain
- `Verify` it launches domain purchase flow as before

Test 2
- For completeness, also verify with a site that has a paid plan
- `Verify` it doesn't display the card above, but the card as before

-----

## Regression Notes

1. Potential unintended areas of impact

    - None

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual, and unit tests

3. What automated tests I added (or what prevented me from doing so)

    - Updated unit tests

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-12-19 23:46 UTC, irfano requested changes
The code change LGTM! 👍🏻 
Also, we may need to change the design depending on the discussion: p1702984046790589-slack-C06AMD6LSPN

The only issue I discovered is on the horizontal mode, sharing here:
<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/b38ce8e6-db26-47e5-96ba-3baa858033ba">

2023-12-20 00:30 UTC, ravishanker commented
> The code change LGTM! 👍🏻 Also, we may need to change the design depending on the discussion: p1702984046790589-slack-C06AMD6LSPN
> 
> The only issue I discovered is on the horizontal mode

Thanks Irfan.  Update to the latest design, fixed landscape orientation as well.

2023-12-20 19:12 UTC, irfano commented
The layout issue has been resolved with your commit. 👍🏻 
The new design looks good, even though you didn't have access to the Figma file, your design is pretty close it. I made minor updates to the style to align with the Figma file.

2023-12-20 19:12 UTC, irfano approved these changes

2023-12-20 22:30 UTC, merged