Stats Traffic invoke traffic tab from widgets
wordpress-mobile/WordPress-Android pull request #20294
Opened 2024-02-27 05:05 UTC by ravishanker

Fixes # https://github.com/wordpress-mobile/jetpack-issue-repo/issues/17

Updates the home screen widgets to invoke Traffic tab where required.

-----

| Widgets | Widgets |
|--------|--------|
| ![Screenshot_20240227_155137](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/f0ee467c-a58c-477f-a02f-c26e18c59dcf) | ![Screenshot_20240227_155152](https://github.com/wordpress-mobile/WordPress-Android/assets/990349/f5b48493-5a08-42d0-8499-a79b02e61a86)| 

## To Test:
- Enable `stats_traffic_tab` feature flag (Me -> Debug settings - Remote Features)
- **Restart** the app
- Go to Stats
- `Verify` only Traffic tab, and Insights tabs are shown 
- `Long press` on the app icon in the launcher on device home screen
- `Select` Widgets
- `Long press` on each of the widgets below
- `Add` it to home screen
- `Follow` the prompt to configure the widget with a Site, Colour, and a View as required

#### 1. At a glance widget
- `Ensure` it open in Traffic tab when feature flag is enabled

#### 2. All-time widget
- There's no change here as All-time card is only available on Insights
- `Ensure` it open in Insights tab as before even when feature flag is enabled 

#### 3. Today widget
- `Ensure` it open in Traffic tab when feature flag is enabled

#### 4. Views this week widget
- `Ensure` it open in Traffic tab when feature flag is enabled

#### 5. Views widget
- `Ensure` it open in Traffic tab when feature flag is enabled
- `Tap` on each rows like Today or a date
- `Verify` that it open the respective date views

- Finally
- Disable the feature flag
- Test each of the widgets opens in Insights or tabs respectively as before

-----

## Regression Notes

1. Potential unintended areas of impact

    - TODO

11. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Tested with, and without feature flag, and existing unit tests

12. What automated tests I added (or what prevented me from doing so)

    - Updated existing tests

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist:

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

2024-02-27 16:02 UTC, irfano requested changes
@ravishanker, I think widgets should work as before. Currently, all widgets open INSIGHTS except the last "Views this week" widget. So, I think that when the flag is enabled, all widgets should still open INSIGHTS, the last "Views this week" widget should open the TRAFFIC tab, with "By day" granularity selected.

2024-02-28 00:41 UTC, ravishanker commented
> @ravishanker, I think widgets should work as before. Currently, all widgets open INSIGHTS except the last "Views this week" widget. So, I think that when the flag is enabled, all widgets should still open INSIGHTS, the last "Views this week" widget should open the TRAFFIC tab, with "By day" granularity selected.

We remove Todays Stats card as well from Insights when feature flag enabled.  Let's also ask @staskus, how's it being handled on iOS.

2024-02-28 08:04 UTC, staskus commented
@ravishanker, @irfano 

This is how it works on iOS now:
https://github.com/wordpress-mobile/WordPress-Android/assets/4062343/3c3ef8f6-fe2f-4d67-980e-31d702b5b00b

- Today Widget -> Traffic (By day)
- This Week Widget -> Traffic (by week)
- All Time Widget -> Insights

2024-02-28 08:35 UTC, irfano approved these changes
Since Ravi reminded me that we removed the Today card from INSIGHTS, and this PR aligns with the current iOS way, this LGTM! 👍🏻 Merging now.

2024-02-28 08:35 UTC, merged

2024-02-28 13:46 UTC, staskus commented
@irfano, @ravishanker 

I'm testing trunk now and clicking Today widget doesn't open Day Traffic view. It only opens Traffic tab and it stays on the previous period (for example By month).

https://github.com/wordpress-mobile/WordPress-Android/assets/4062343/df51c9be-d1c6-43a4-b573-9699bb7c1af8

2024-02-28 19:12 UTC, irfano commented
Thanks @staskus ! I also noted that in https://github.com/wordpress-mobile/WordPress-Android/pull/20294#pullrequestreview-1903992799 but then forgot it and merged the PR. 🤦🏻‍♂️

I'm fixing it with https://github.com/wordpress-mobile/WordPress-Android/pull/20316