Issue/20189 post sync before editing
wordpress-mobile/WordPress-Android pull request #20301
Opened 2024-02-27 16:19 UTC by pantstamp

Fixes #
#20189
-----

This PR adds a check when user tries to edit a post so we can determine if we need to refetch it. In this way we try to minimise the chances to have version conflicts. There are some modifications needed in the FluxC library so there is an associated [PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2957).

**This PR targets trunk but we might need to merge this to a feature branch instead.** 

## To Test:

1. Install and launch the JP app from this PR
2. Choose a site and create a new post. 
3. Check that everything works alright. 
4. Wait for more that 20 second in the post list screen. 
5. Tap on the post that you created. Check that a new message appears saying "Updating post content" and at the same time user cannot modify the post. 
6. Check that after a while this message disappears and user can edit the post. 
7. Make some changes in the content and update the post. 
8. While staying in the post list screen, use your laptop's browser to launch WordPress.com, find this post and update its content.
9. Go back to your mobile device and tap the same post in the list. 
10. Check that the "updating post" message appears and you see the updated content. 
11. Make some local changes and tap back without updating the post.
12. check that the "Local changes" label appears for this post.
13. Go to WordPress.com and make some changes in this post. 
14. Go back to your mobile device and tap on the same post from the list. 
15. Check that there is no "Updating" message and you see the local changes only and not the changes you made on web.

-----

## Testing Checklist:

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

2024-02-27 16:19 UTC, dangermattic commented
<!--
  2 Errors: Please add tests for class <co...
  2 Warnings: <code>strings.xml</code> files...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>SystemTimeProvider</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>strings.xml</code> files should only be updated on release branches, when the translations are downloaded by our automation.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-03-05 20:55 UTC, zwarm requested changes
@pantstamp -

👏  Thank you for wrapping the logic in the feature flag. 🙇 

All is working as expected; however the updating post content view doesn't feel like a smooth transition. Take a look at the video I captured on my Pixel 5. Not sure if this is because my internet is speedy, but I wonder if there is a way to improve the transition and allow the user to read that we are refreshing the post? 

https://github.com/wordpress-mobile/WordPress-Android/assets/506707/471a7002-7d0f-4b05-9a2d-7f6274b061c7

💬 FYI ... general consensus in the WP code base is to favor composition over inheritance. To be clear, I am NOT asking for a change. Rather have a think on what a composition implementation would look like (ie: removing `IPostFreshnessChecker` and `PostModule`). Could the logic be moved out PostUtilsWrapper into a standalone class (Use PostFreshnessCheckerImpl without the interface)? Or maybe alter the shouldRefershPost fun to `fun shouldRefreshPost(post: PostImmutableModel, currentTimeProvider: () -> Long): Boolean`. 

Something to ponder.

2024-03-06 10:31 UTC, pantstamp commented
Hey @zwarm , thanks for reviewing my PR! After watching the video that you recorded, I will definitely try to come up with a fix for this. My internet connection is not so speedy, so I had never witnessed this less than smooth transition.

For the architectural part, I really enjoy these kinds of conversations, so thank you for that! I am also a fan of composition over inheritance. From my point of view, the use of interfaces does not violate this practice as I am not creating a complex inheritance hierarchy. The reason why I chose to use an interface here is that I wanted to create an abstraction for the post freshness checker as requirements might change in the future, and we might need a different "algorithm" to determine when a post needs to be refetched. With the current implementation, we will just create a new object that implements the contract of IPostFreshnessChecker and pass it to the other components with dependency injection.

The reason that I injected the PostFreshnessChecker into PostUtilsWrapper is just for consistency, as I saw that the StorePostViewModel is already using it. We could inject this directly into StorePostViewModel if you think that is a better approach.

Altering the shouldRefreshPost function to `fun shouldRefreshPost(post: PostImmutableModel, currentTimeProvider: () -> Long): Boolean` could make the code more concise and remove the need for the TimeProvider interface. The reason why I added this is for improving testability, but we could achieve the same result without it.

Of course, I have no issues removing the interface if there is consensus in the WP code base not to use interfaces unless they are necessary. 

Have I missed anything else? Do you think the current implementation will cause any issues in the future related to the maintainability and flexibility of the feature?

2024-03-06 18:35 UTC, zwarm commented
>  I will definitely try to come up with a fix for this. My internet connection is not so speedy, so I had never witnessed this less than smooth transition.

🙇  thanks

> For the architectural part, I really enjoy these kinds of conversations

❤️ 

> The reason that I injected the PostFreshnessChecker into PostUtilsWrapper is just for consistency, as I saw that the StorePostViewModel is already using it. We could inject this directly into StorePostViewModel if you think that is a better approach.

What you have works. Personally, we all approach problems differently and it's nice to share. I probably wouldn't have moved the checker into the utilsWrapper and instead injected it separately. The `PostUtilsWrapper` is wrapping static classes to make them easier to test. We don't need to do that with `PostFreshnessCheckerImpl`; it's not a class with static methods. I would have probably eliminated the DI module too and directly marked the `PostFreshnessCheckerImpl` class as a Singleton and use @inject constructor. Neither approach is wrong; just different.

> Altering the shouldRefreshPost function to fun shouldRefreshPost(post: PostImmutableModel, currentTimeProvider: () -> Long): Boolean could make the code more concise and remove the need for the TimeProvider interface. The reason why I added this is for improving testability, but we could achieve the same result without it.

+1 on testability, so thank you.


> Of course, I have no issues removing the interface if there is consensus in the WP code base not to use interfaces unless they are necessary.

Nope, you don't need makes any changes and that was not my intent with the comment. But thanks for taking the time to consider things.

> Have I missed anything else? Do you think the current implementation will cause any issues in the future related to the maintainability and flexibility of the feature?

No, all should be okay.

2024-03-06 18:45 UTC, zwarm approved these changes
@pantstamp - ❤️ on the delay for updating post content; it no longer flashes quickly. I am approving the PR, but will leave the merging up to you. Nice work.

2024-03-07 06:29 UTC, AjeshRPai approved these changes
Hey @pantstamp 

I tested the changes per the instructions, and everything looks good 👍🏼 . Approving but not merging so that this PR can be updated after merging the FLUXC PR. 

Left a nitpick, feel free to update or ignore that change if you think that's not necessary.

2024-03-07 06:29 UTC, AjeshRPai commented on WordPress/src/main/java/org/wordpress/android/util/config/SyncPublishingFeatureConfig.kt
> +@Feature(SYNC_PUBLISHING_FEATURE_REMOTE_FIELD, false)
Nitpick: Can we pass the `BuildConfig.SYNC_PUBLISHING` as the default value here as well 🤔

2024-03-07 16:05 UTC, merged