[Hack] Add logic to BuildConfig to allow for announcement debugging.
wordpress-mobile/WordPress-Android pull request #20486
Opened 2024-03-15 21:02 UTC by notandyvee

The current announcement logic is a bit of a pain to test. Normally I'd add a feature flag. But I thought instead let's add something in build.gradle to use local.properties so it's a bit easier to test.

Now you can simply add `alwaysShowAnnouncement=true` to your `local.properties`, build the app in debug, and the announcements from your current release should be shown every time you load the app.

Thoughts?

-----

## To Test:

- [ ] Install the apk from this PR and make sure you aren't seeing an announcement on a fresh install.
- [ ] uninstall the previous apk and install a previous version (24.3.1). Login.
- [ ] Now install this apk.
- [ ] You should see the stats announcement.
- [ ] Now checkout this PR and build it locally.
- [ ] You should not see the announcement.
- [ ] Add `alwaysShowAnnouncement=true` to your `local.properties` file and rebuild. You should be seeing the announcement pop up on app load everytime.

-----

## Regression Notes

1. Potential unintended areas of impact

    n/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    Manual test.

3. What automated tests I added (or what prevented me from doing so)

    n/a

-----

## PR Submission Checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2024-03-15 21:03 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-03-26 13:32 UTC, guarani commented
👋 My setup wasn't working so I couldn't test. See https://a8c.slack.com/archives/C441E3YTS/p1711413127791989?thread_ts=1711405412.749429&cid=C441E3YTS for details.

2024-03-31 14:32 UTC, irfano commented
@notandyvee, I am the reviewer but the PR is still draft. Is this ready for review?

2024-04-15 16:34 UTC, notandyvee commented
Apologies @irfano I just haven't had time. Let me carve out time today to make the documentation and then convert it to a final PR. Since Paul was having trouble it became clear it needs some documentation.

2024-04-15 21:18 UTC, notandyvee commented
It's ready @irfano . I held off on writing some docs until I hear what you think. Please note this PR does not need to be merged. If you feel strongly against adding this, we can close and consider a different way of accomplishing the same thing. No pressure. Adding @aditi-bhatia to the reviewers to get some more opinions.

2024-04-16 01:42 UTC, aditi-bhatia approved these changes
Looks good to me, this is useful to have added in 👍 I was unable to test the `extra credit` with the release build because of some issues, but all other steps worked as expected. I'll try the release build again tomorrow but not expecting any issues with that

2024-04-16 15:20 UTC, irfano commented
I added `alwaysShowAnnouncement=true` to `local.properties` and built `jetpackWasabiDebug` but couldn't see the announcement. What am I missing? 🤔

2024-04-16 15:36 UTC, notandyvee commented
> I added alwaysShowAnnouncement=true to local.properties and built jetpackWasabiDebug but couldn't see the announcement. What am I missing? 🤔

I don't use wasabi. This could be another area of concern. Could you try jalapeno first to see whatsup?

2024-04-16 15:51 UTC, irfano commented
Our purpose of this is to see how the announcement will look on the screen, right? I find putting a config in the Debug settings screen preferable because testers who are not Android developers can also utilize this setting. WDYT?

I noticed that iOS has some buttons for similar features on its Debug settings screen. We can do the same.

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/8c8bbedd-2d1f-49af-865a-31b9c7fed2ac" width=320>

2024-04-16 21:13 UTC, notandyvee commented
> I noticed that iOS has some buttons for similar features on its Debug settings screen. We can do the same.

I'll need some time to look into how iOS is doing it. Android's is a bit clunky, which is why I decided against it. But sure.

2024-04-17 19:36 UTC, irfano commented
We have a "FEATURES IN DEVELOPMENT" tab in the "Debug settings". Perhaps we can add a fourth tab to this screen, "LOCAL CONFIGS", and use the same design as "FEATURES IN DEVELOPMENT.

I believe being able to find everything related to testing configs within "Debug settings" would be a better option.

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/9a1c6d77-a96a-415b-8493-efbd801eb745" width=320>

2024-04-22 06:04 UTC, ravishanker commented
It appeared to me on trunk build once.  Is that the upgrade to 24.7 scenario showing up?

<img width=320 src=https://github.com/wordpress-mobile/WordPress-Android/assets/990349/109ef85c-f6e4-4739-a3c0-e1e5c9050b51 />

2024-04-22 06:06 UTC, ravishanker commented
> We have a "FEATURES IN DEVELOPMENT" tab in the "Debug settings". Perhaps we can add a fourth tab to this screen, "LOCAL CONFIGS", and use the same design as "FEATURES IN DEVELOPMENT.
> 
> I believe being able to find everything related to testing configs within "Debug settings" would be a better option.
> 


You could just add it to Features in development tab, and stays there forever.

2024-05-10 19:52 UTC, dangermattic commented
<!--
  2 Errors: Please add tests for class <co...
  1 Warning: <code>strings.xml</code> files...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>SharedPrefsField</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>SharedPrefsBooleanField</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>strings.xml</code> files should only be updated on release branches, when the translations are downloaded by our automation.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-05-10 21:51 UTC, notandyvee commented
@irfano sorry I didn't get to this sooner. Mind taking a look when you get a chance and give me your thoughts. I did what was mentioned. Add a new tab on the debug settings screen. I decided to create a new `UiItem`, `SharedPrefsField`. This item currently only represents a boolean, but can be a string, long, etc. Hence why I am using a type. I tried to keep it simple since it's only for debugging.

2024-05-11 11:22 UTC, irfano commented
@notandyvee, while reviewing the change, I noticed a screen that already contains your new pref, `pref_always_show_announcement`. This screen was introduced 4 months ago (#19880). Do you think we can just add a new pref and use this existing screen?
 <img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/4707ebb0-5fe1-4dad-ab9f-99f698d03cd5" width=300> <img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/c665438f-fbf1-49cf-8caa-04c09f62f989" width=300>

2024-05-11 17:20 UTC, notandyvee commented
> @notandyvee, while reviewing the change, I noticed a screen that already contains your new pref, pref_always_show_announcement. This screen was introduced 4 months ago (https://github.com/wordpress-mobile/WordPress-Android/pull/19880). Do you think we can just add a new pref and use this existing screen?

Sigh 🤦🏻‍♂️ . I do think we should re-use that screen. Just sucks we didn't catch that sooner. Gonna be the 3rd iteration. I'll look into it on monday.

2024-05-13 22:13 UTC, notandyvee commented
@justtwago I made some edits to `DebugSharedPreferenceFlagsViewModel` that require your approval. I needed a debug shared pref value for debugging. Since the shared pref needs to be written first before it's seen on that screen, I thought it made more sense to add any flags we want to test in a list of enums. This way any test ones can be toggled.

The other big reason I felt this change would be helpful is to open it up for strings and other primitive types. Maybe test urls or other text we can change for debug purposed. I didn't make that change as it's not required yet, but it's why I added `KClass` in the `DebugPrefs` enum. Thoughts?

2024-05-14 11:43 UTC, irfano requested changes
It's a great solution Andy, I like it. Adding some notes:

- Now, I can only see `pres_always_show_announcement`.

|before|after|
|-|-|
|<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/21cbb7b3-c18b-41f7-849f-a9d26f4b7af6" width=300>|<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/dd6c5c9f-325b-4ecc-935c-1ad3dbdfd004" width=300>|

2024-05-14 11:43 UTC, irfano commented on WordPress/src/main/java/org/wordpress/android/ui/debug/preferences/DebugPrefs.kt
> + */
What does "Class used to track" mean?

2024-05-14 15:18 UTC, notandyvee commented
@irfano I'll fix the failing test.

> What does "Class used to track" mean?

I started to add class doc and stopped mid way 😅 . Updated now.

> Now, I can only see pres_always_show_announcement

This is on purpose. It's why I pinged @justtwago . Currently the preference flag needs to exist in order for it to show up. I just updated it to be more explicit. If you have no issues feel free to approve, but **do not merge**. We can wait for Arty to put his opinion.

2024-05-14 16:02 UTC, irfano approved these changes

2024-05-14 16:10 UTC, justtwago commented
Really nice idea, Andy! Thanks for pinging me!
I'm sorry that the debug screen I introduced wasn't clearly described. The initial idea was to display all the locally stored flags so we could test/reset them without clearing the cache/local data. My motivation was the "Dynamic dashboard cards" project (PCYsg-W09-p2). Once we tap on "Hide" from a card's menu, it creates a shared pref for this particular card to stop displaying it on the dashboard. The only way to reset or "unhide" it was by clearing the cache and going through the authentication process again.

What if we combined the two lists to display some app-managed flags and the predefined debug flags that you introduced?

2024-05-14 16:11 UTC, justtwago commented on WordPress/src/main/java/org/wordpress/android/ui/debug/preferences/DebugSharedPreferenceFlagsViewModel.kt
> +        }.associate { it.key to prefsWrapper.getDebugBooleanPref(it.key, false) }
Really nice idea, Andy! Thanks for pinging me!
I'm sorry that the debug screen I introduced wasn't clearly described. The initial idea was to display all the locally stored flags so we could test/reset them without clearing the cache/local data. My motivation was the "Dynamic dashboard cards" project (PCYsg-W09-p2). Once we tap on "Hide" from a card's menu, it creates a shared pref for this particular card to stop displaying it on the dashboard. The only way to reset or "unhide" it was by clearing the cache and going through the authentication process again.

What if we combined the two lists to display app-managed flags and the predefined debug flags that you introduced?

2024-05-14 16:13 UTC, justtwago commented on WordPress/src/main/java/org/wordpress/android/ui/debug/preferences/DebugSharedPreferenceFlagsViewModel.kt
> +        }.associate { it.key to prefsWrapper.getDebugBooleanPref(it.key, false) }
This is the context: pcdRpT-5f2-p2
I should've linked it to my PR 🤦‍♂️

2024-05-14 18:05 UTC, notandyvee commented on WordPress/src/main/java/org/wordpress/android/ui/debug/preferences/DebugSharedPreferenceFlagsViewModel.kt
> +        }.associate { it.key to prefsWrapper.getDebugBooleanPref(it.key, false) }
> What if we combined the two lists to display some app-managed flags and the predefined debug flags that you introduced?

I went ahead and merged the two maps. Would be great if you could do a review @justtwago 🙏🏻

2024-05-14 18:45 UTC, justtwago approved these changes
Thanks so much for the improvement! LG2M! 🎸

2024-05-14 20:28 UTC, merged