Update empty Stats display to match iOS
wordpress-mobile/WordPress-Android pull request #20605
Opened 2024-04-06 00:34 UTC by aditi-bhatia

Fixes #

-----

## To Test:

-----

## Regression Notes

1. Potential unintended areas of impact

    - TODO

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - TODO

3. What automated tests I added (or what prevented me from doing so)

    - TODO

-----

## PR Submission Checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

2024-04-06 00:34 UTC, dangermattic commented
<!--
  1 Error: PR requires at least one label...
  1 Warning: PR is not assigned to a milest...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-04-08 21:50 UTC, irfano requested changes
If we're not going to draw empty bars, why should we still set gradient color, form line width, and other settings? I think we can remove `buildEmptyDataSet()` function and have `BarChart.draw()` return 0 for empty bars. WDYT?

2024-04-15 23:53 UTC, aditi-bhatia commented
Hi @irfano thanks for taking a look and I agree that these operations seem unnecessary. The gradient color has to be set since the default color for an empty data set is this color: 
<img width="287" alt="Screenshot 2024-04-15 at 4 51 26 PM" src="https://github.com/wordpress-mobile/WordPress-Android/assets/7199140/265c9302-5254-4098-8d24-0db9657218c9">
I can go ahead and remove the line width and other customizations since that is not needed for transparent bars. What do you think?

2024-04-16 00:15 UTC, aditi-bhatia commented
Hi @irfano, thanks for your review and I agree that setting these values feels redundant. I'm setting the bar `gradient color` as transparent because I believe the chart library sets a default color on bar displays, even for empty data: 
<img width="287" alt="Screenshot 2024-04-15 at 4 51 26 PM" src="https://github.com/wordpress-mobile/WordPress-Android/assets/7199140/d8d1e7d2-1b5e-4a7e-8fff-8817824914b0">
I can go ahead and remove the line width and other settings since that is unnecessary for transparent bars. What do you think?

2024-04-16 14:09 UTC, irfano requested changes
> I believe the chart library sets a default color on bar displays, even for empty data:

We set the values to "1f" in  `buildEmptyDataSet()`, which is why we're seeing bars. We should completely remove buildEmptyDataSet() and use `BarDataSet(emptyList(), "Empty")` in `BarChart.draw()` where we call `buildEmptyDataSet()`. 

I tested it, and it prevents bars from being drawn.

2024-04-16 22:42 UTC, aditi-bhatia commented
Hi @irfano thank you for looking into it! I completely missed the part where the values were being set to `1f` 😅 I've made the changes in both `TrafficBarChartViewHolder.kt` and `BarChartViewHolder.kt` since I'm not sure if we're planning to remove the first one.

2024-04-17 19:52 UTC, irfano approved these changes
Thank you for addressing my comments! LGTM! 

> I'm not sure if we're planning to remove the first one.

It's better to remove empty bars from both view holders since this is now matching with the iOS. 👍🏻

2024-04-17 19:52 UTC, merged