[Deps] Add Back EventBus Android Dependency
wordpress-mobile/WordPress-Android pull request #21252
Opened 2024-09-23 16:11 UTC by ParaskP7

## Description

This PR adds back the main `EventBus` dependency, which is `Android` related.

This dependency was incorrectly removed and replaced by its corresponding `eventbus-java` transitive dependency, assuming that is not required. However, after further testing it was revealed that this parent `eventbus` dependency, which is actually `android` specific is indeed necessary. If it is not provided on the classpath then an app will crash with the below runtime exception:

```
java.lang.RuntimeException: Unable to create application xyz: java.lang .RuntimeException:
It looks like you are using EventBus on Android, make sure to add the "eventbus" Android
library to your dependencies.
```

For more info see:
- [EventBus.register(...)](https://github.com/greenrobot/EventBus/blob/0194926b3bcf70cc0d7bfd3c5da16708dd5ab876/EventBus/src/org/greenrobot/eventbus/EventBus.java#L143-L147)
- [!AndroidDependenciesDetector.areAndroidComponentsAvailable()](https://github.com/greenrobot/EventBus/blob/0194926b3bcf70cc0d7bfd3c5da16708dd5ab876/EventBus/src/org/greenrobot/eventbus/android/AndroidDependenciesDetector.java#L25-L36)

-----

## To Test:

1. Tooling:
    - Run the `./gradlew buildHealth` task and verify that there is no `unused` related advise related to `eventbus`.
2. Testing:
    - Smoke test both, the `Jetpack` and `WordPress`  apps and verify everything is working as expected.

-----

## Regression Notes (`N/A`)

-----

## PR Submission Checklist: (`N/A`)

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones): (`N/A`)

2024-09-23 18:44 UTC, jkmassel requested changes
Could we have a failing test case for this?

2024-09-24 07:46 UTC, ParaskP7 commented
👋 @jkmassel and thanks for taking a look! 🙇 

> Could we have a failing test case for this?

Actually, we already have failing tests for this case, all and any of our UI tests would fail when the condition above would have met. This is just me being proactive on that, fixing this problem before it even appears in front of us, us updating [WordPress-Utils](https://github.com/wordpress-mobile/WordPress-Utils-Android) in the future. ✅ 

FYI: You could also check this (p1727160993008069/1727109960.755359-slack-C04PWEZSYFL) thread where I try to explain this in more detail to @nbradbury. 🙏

2024-09-24 08:03 UTC, wzieba approved these changes

2024-09-25 07:47 UTC, ParaskP7 commented
👋 @jkmassel !

Do you mind taking another look at [this](https://github.com/wordpress-mobile/WordPress-Android/pull/21252#issuecomment-2370451640) and hopefully lift the change requested review as this approved PR is now blocked from merging without you doing that. 🙏

2024-09-26 15:28 UTC, jkmassel approved these changes
@ParaskP7 pointed out that this issue should be caught simply by launching the app in a dev environment, so while a test would be a nice backup it's not necessarily the right answer.

2024-09-26 15:31 UTC, merged