Support dark mode in Zendesk chat
wordpress-mobile/WordPress-Android pull request #21486
Opened 2024-11-22 19:34 UTC by nbradbury

Fixes #21485 

Previously Zendesk chat would show with light mode colors even in dark mode. This PR addresses this. I also updated to the latest Zendesk library while I was at it.

To test:

* Enable dark mode either in the app or the device
* Me > Help & support > Contact Support
* Verify the chat screen uses dark colors
* Disable dark mode and verify the chat screen uses light colors

![dark](https://github.com/user-attachments/assets/07024f23-a3cf-4fcf-a13d-23b279e548a2)

2024-11-22 19:39 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-11-25 21:52 UTC, jkmassel requested changes
Is it possible to use the same fix for the "My Tickets" list?

![Screenshot_20241125_145158](https://github.com/user-attachments/assets/0809b1ca-a5c0-4dbd-84d0-2b71e6102c47)

2024-11-26 18:12 UTC, nbradbury commented
> Is it possible to use the same fix for the "My Tickets" list?

Unfortunately, the same fix won't work for that screen (`RequestListActivity`). [According to the Zendesk docs](https://developer.zendesk.com/documentation/classic-web-widget-sdks/unified-sdk/android/customizing_the_look/) that screen should automatically support dark mode, but it does not. I'll file a separate issue for this.

2024-11-27 01:19 UTC, jkmassel approved these changes

2024-11-27 01:19 UTC, merged