Latest post summary block
wordpress-mobile/WordPress-Android pull request #8448
Opened 2018-10-18 09:18 UTC by planarvoid

Fixes #8332 
Adds `Latest post summary` block to the new Stats. What's still missing in the block is the Graph. The block has 3 states - an empty state, when there is no post yet published, a state when there is a latest post but it had no interactions yet and the normal state with 3 columns with views, comments and likes
The bottom button doesn't have an action attached yet. 

There will be another PR with the actions and tests and the graph.

To test:
* go to Stats
* you see the Latest post summary block on top of the list

2018-10-18 20:05 UTC, 0nko reviewed
👍. Please see the code comments.

2018-10-22 15:03 UTC, planarvoid commented
@0nko everything should be fixed 👍

2018-10-22 17:32 UTC, 0nko requested changes
Thanks for the changes. 

There's just one issue with the link: If `StatsBlockLine` used paddings instead of a margin, the selectable background would extend the entire width of a block.

2018-10-22 17:32 UTC, 0nko commented on WordPress/src/main/res/layout/stats_block_link_item.xml
> +              style="@style/StatsBlockLine"
The button/link is missing a click feedback
```suggestion
              style="@style/StatsBlockLine"
              android:background="?attr/selectableItemBackground"
```

2018-10-23 09:07 UTC, planarvoid commented
@0nko thanks for the feedback! I've replaced margin with padding and approved your change 👍

2018-10-23 10:02 UTC, 0nko approved these changes
Looks good!

2018-10-24 07:39 UTC, merged