Create tags and categories block
wordpress-mobile/WordPress-Android pull request #8617
Opened 2018-11-16 13:21 UTC by planarvoid

Fixes #8530 
This PR creates a new block with expandable tags and categories in the Stats. Clicking a tag redirects the use to the Tag detail in a `WebView`. Clicking "View more" opens a full list of tags and categories in the previous design. 

The expanded category should keep it's state on orientation changes.

To test:
* Open stats
* You see the Tags and Categories block
* Clicking on a category expands the tags in that category
* Clicking on a Tag opens a WebView
* Clicking on View More opens a new activity with a longer list of Tags and categories

2018-11-20 23:28 UTC, 0nko requested changes
I left a few minor comments, otherwise it looks great! 👍

2018-11-22 10:30 UTC, planarvoid commented
@0nko I think this is ready for another check

2018-11-22 11:13 UTC, 0nko approved these changes

2018-11-22 11:13 UTC, 0nko commented
:shipit:

2018-11-22 11:14 UTC, merged